/******************************************************************************/
/*
 * Copyright (C) 1994-2014 EcoNet Technologies, Corp.
 * All Rights Reserved.
 *
 * TrendChip Confidential; Need to Know only.
 * Protected as an unpublished work.
 *
 * The computer program listings, specifications and documentation
 * herein are the property of TrendChip Technologies, Corp. and
 * shall not be reproduced, copied, disclosed, or used in whole or
 * in part for any reason without the prior express written permission of
 * TrendChip Technologies, Corp.
 */
/******************************************************************************/
//#include <stdlib.h>
#ifdef __KERNEL__
#include <linux/init.h>
#include <linux/mm.h>
#include <linux/sched.h>
#include <linux/bootmem.h>
#include <linux/blkdev.h>

#include <asm/mipsmtregs.h>
#include <asm/addrspace.h>
#include <asm/bootinfo.h>
#include <asm/cpu.h>
#include <asm/time.h>
#include <asm/traps.h>

#include <linux/libcompileoption.h>
#else
#include "libcompileoption.h"
#endif

CompileOption_Val TCSUPPORT_CT_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_VLAN_TAG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_VLAN_TAG_VAL);
#endif

CompileOption_Val TCSUPPORT_VLAN_TAG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VLAN_TAG_VAL);
#endif

CompileOption_Val TCSUPPORT_TCAPI_ENHANCE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TCAPI_ENHANCE_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_C5_2P_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_C5_2P_VAL);
#endif

#if 0
CompileOption_Val TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL);
#endif
#endif

CompileOption_Val TCSUPPORT_CT_PON_GD_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_GD_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_GDV20_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_GDV20_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CZ_GDCS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CZ_GDCS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CY_VAL);
#endif

CompileOption_Val TCSUPPORT_ZARLINK_LE89156A_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ZARLINK_LE89156A_VAL);
#endif

CompileOption_Val TCSUPPORT_ZARLINK_LE89156B_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ZARLINK_LE89156B_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CY_JX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CY_JX_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_BIND2_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_BIND2_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_JS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_JS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_FJ_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_FJ_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_GX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_GX_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CQ_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CQ_VAL);
#endif


CompileOption_Val TCSUPPORT_CT_UPG_PINGPONG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_UPG_PINGPONG_VAL);
#endif

CompileOption_Val TCSUPPORT_BACKUPROMFILE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_BACKUPROMFILE_VAL);
#endif

CompileOption_Val TCSUPPORT_PRODUCTIONLINE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PRODUCTIONLINE_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_CWMP_PARAMETER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_CWMP_PARAMETER_VAL);
#endif

CompileOption_Val TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_MIDWARE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_MIDWARE_VAL);
#endif

CompileOption_Val TCSUPPORT_CDS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CDS_VAL);
#endif

CompileOption_Val TCSUPPORT_VLAN_DOT1P_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VLAN_DOT1P_VAL);
#endif

CompileOption_Val TCSUPPORT_VLAN_PASSTHROUGH_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VLAN_PASSTHROUGH_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_FJ_SFU_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_FJ_SFU_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_VAL);
#endif

CompileOption_Val TCSUPPORT_CY_PON_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CY_PON_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PHONEAPP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PHONEAPP_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_C9_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_C9_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_JS_IP_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_JS_IP_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_VOIP_CRYPT_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_VOIP_CRYPT_VAL);
#endif

CompileOption_Val TCSUPPORT_VOIP_LED_APPCTRL_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VOIP_LED_APPCTRL_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_FH_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_FH_VAL);
#endif

CompileOption_Val TCSUPPORT_VOIP_SIP_DNS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VOIP_SIP_DNS_VAL);
#endif


CompileOption_Val TCSUPPORT_AUTOBENCH_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_AUTOBENCH_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_YN_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_YN_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ECN_GZ_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ECN_GZ_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_WANNINDEX_INCREASE_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_WANNINDEX_INCREASE_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_MONITORCOLLECTOR_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_MONITORCOLLECTOR_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PPPOE_EMULATOR_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PPPOE_EMULATOR_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_NMG_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_NMG_VAL);
#endif

CompileOption_Val TCSUPPORT_CY_E8_SFU_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CY_E8_SFU_VAL);
#endif

CompileOption_Val CT_COM_DEVICEREG_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(CT_COM_DEVICEREG_VAL);
#endif

CompileOption_Val TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL);
#endif

CompileOption_Val TCSUPPORT_DMS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_DMS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_UPNP_DM_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_UPNP_DM_VAL);
#endif

CompileOption_Val TCSUPPORT_TR69_IP_HOST_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TR69_IP_HOST_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_IP_HOST_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_IP_HOST_VAL);
#endif

CompileOption_Val TCSUPPORT_C1_MS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C1_MS_VAL);
#endif

CompileOption_Val TCSUPPORT_C1_ZY_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C1_ZY_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PPPINFORM_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PPPINFORM_VAL);
#endif

CompileOption_Val TCSUPPORT_PONMGR_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PONMGR_VAL);
#endif

CompileOption_Val TCSUPPORT_PMMGR_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PMMGR_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_ATM_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_ATM_VAL);
#endif

CompileOption_Val TCSUPPORT_CPU_MT7505_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CPU_MT7505_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_SWQOS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_SWQOS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_SIMCARD_SEPARATION_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_SIMCARD_SEPARATION_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_2PORTS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_2PORTS_VAL);
#endif

CompileOption_Val TCSUPPORT_LAN_VLAN_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_LAN_VLAN_VAL);
#endif

CompileOption_Val TCSUPPORT_LAN_VLAN_RANGE_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_LAN_VLAN_RANGE_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_SN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_SN_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_WAN_PTM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_WAN_PTM_VAL);
#endif

CompileOption_Val TCSUPPORT_C1_CUC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C1_CUC_VAL);
#endif

CompileOption_Val TCSUPPORT_SYSLOG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_SYSLOG_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PORT_BIND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PORT_BIND_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_GUIACCESSLIMIT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_GUIACCESSLIMIT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PPPOEPROXY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PPPOEPROXY_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ZIPROMFILE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ZIPROMFILE_VAL);
#endif

CompileOption_Val TCSUPPORT_RESERVEAREA_EXTEND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_RESERVEAREA_EXTEND_VAL);
#endif

CompileOption_Val TCSUPPORT_C7_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C7_VAL);
#endif

CompileOption_Val TCSUPPORT_CY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CY_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_E8B_ADSL_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_E8B_ADSL_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_WANNODE_MAPPING_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_WANNODE_MAPPING_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_BLOCK_PROCESS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_BLOCK_PROCESS_VAL);
#endif

CompileOption_Val TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL);
#endif

CompileOption_Val TCSUPPORT_CPU_MT7510_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CPU_MT7510_VAL);
#endif

CompileOption_Val TCSUPPORT_CPU_MT7520_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CPU_MT7520_VAL);
#endif

CompileOption_Val RA_NAT_EXE_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(RA_NAT_EXE_VAL);
#endif

CompileOption_Val TCSUPPORT_TRUE_LANDING_PAGE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TRUE_LANDING_PAGE_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_NO_HOST_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_NO_HOST_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_VAL);
#endif

CompileOption_Val TCSUPPORT_INIC_CLIENT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_INIC_CLIENT_VAL);
#endif

CompileOption_Val TCSUPPORT_CZ_GENERAL_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CZ_GENERAL_VAL);
#endif

CompileOption_Val TCSUPPORT_KEYPARA_STORE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_KEYPARA_STORE_VAL);
#endif

CompileOption_Val TCSUPPORT_VPN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VPN_VAL);
#endif

CompileOption_Val TCSUPPORT_MULTI_BOOT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_MULTI_BOOT_VAL);
#endif

CompileOption_Val TCSUPPORT_START_TRAP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_START_TRAP_VAL);
#endif

CompileOption_Val TCSUPPORT_SYSLOG_ENHANCE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_SYSLOG_ENHANCE_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_AC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_AC_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_FAST_GET_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_FAST_GET_VAL);
#endif

CompileOption_Val TCSUPPORT_CD_DDNS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CD_DDNS_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_GPON_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_GPON_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_EPON_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_EPON_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_ETHER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_ETHER_VAL);
#endif

CompileOption_Val TCSUPPORT_OMCI_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_OMCI_VAL);
#endif

CompileOption_Val TCSUPPORT_EPON_OAM_CTC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_EPON_OAM_CTC_VAL);
#endif

CompileOption_Val TCSUPPORT_CMDPROMPT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CMDPROMPT_VAL);
#endif

CompileOption_Val TCSUPPORT_RANDOM_INFORM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_RANDOM_INFORM_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_SERVICELIST_E8C_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_SERVICELIST_E8C_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ALARMMONITOR_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ALARMMONITOR_VAL);
#endif

CompileOption_Val TCSUPPORT_CZ_TM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CZ_TM_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_INFORM_NODE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_INFORM_NODE_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_LONG_RESETBTN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_LONG_RESETBTN_VAL);
#endif

CompileOption_Val CWMP_REDIRECT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(CWMP_REDIRECT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PPP_ONDEMAND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PPP_ONDEMAND_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL);
#endif

CompileOption_Val TCSUPPORT_TR69_BIND_PVC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TR69_BIND_PVC_VAL);
#endif

CompileOption_Val TCSUPPORT_NO_BOOT_VALUECHANGE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_NO_BOOT_VALUECHANGE_VAL);
#endif

CompileOption_Val TCSUPPORT_CROSS_REBOOT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CROSS_REBOOT_VAL);
#endif

CompileOption_Val TCSUPPORT_BHARTI_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_BHARTI_VAL);
#endif

CompileOption_Val TCSUPPORT_TTNET_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TTNET_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_PRECISE_TIME_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_PRECISE_TIME_VAL);
#endif

CompileOption_Val TCSUPPORT_C1_NEW_GUI_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C1_NEW_GUI_VAL);
#endif

CompileOption_Val TCSUPPORT_PROLINE_CMD_ACTION_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PROLINE_CMD_ACTION_VAL);
#endif

CompileOption_Val TCSUPPORT_MULTISERVICE_ON_WAN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_MULTISERVICE_ON_WAN_VAL);
#endif

CompileOption_Val TCSUPPORT_UPNP_ENHANCE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_UPNP_ENHANCE_VAL);
#endif

CompileOption_Val TCSUPPORT_C1_OBM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C1_OBM_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_PTM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_PTM_VAL);
#endif

CompileOption_Val TCSUPPORT_CD_NEW_GUI_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CD_NEW_GUI_VAL);
#endif

CompileOption_Val TCSUPPORT_CCT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CCT_VAL);
#endif

CompileOption_Val TCSUPPORT_CLMP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CLMP_VAL);
#endif

CompileOption_Val TCSUPPORT_SAGECOM_CWMP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_SAGECOM_CWMP_VAL);
#endif

CompileOption_Val TCSUPPORT_FW_UPGRADE_DELAY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FW_UPGRADE_DELAY_VAL);
#endif

CompileOption_Val AZTECH_CWMP_REORDER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(AZTECH_CWMP_REORDER_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_FAULT_RESPONSE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_FAULT_RESPONSE_VAL);
#endif

CompileOption_Val TCSUPPORT_CWMP_CRPORTCHANGE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CWMP_CRPORTCHANGE_VAL);
#endif

CompileOption_Val TCSUPPORT_WEB_INTERCEPTION_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WEB_INTERCEPTION_VAL);
#endif

CompileOption_Val TCSUPPORT_MNT_CONF_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_MNT_CONF_VAL);
#endif

CompileOption_Val TCSUPPORT_FTP_USB_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FTP_USB_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_NEWGUI_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_NEWGUI_VAL);
#endif

CompileOption_Val TCSUPPORT_IPV6_FIREWALL_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_IPV6_FIREWALL_VAL);
#endif

CompileOption_Val TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL);
#endif

CompileOption_Val TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_HWQOS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_HWQOS_VAL);
#endif

CompileOption_Val TCSUPPORT_CHT_RAMENU_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CHT_RAMENU_VAL);
#endif

CompileOption_Val TCSUPPORT_EPON_OAM_LAN_DBG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_EPON_OAM_LAN_DBG_VAL);
#endif

CompileOption_Val TCSUPPORT_E8B_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_E8B_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_VLAN_BIND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_VLAN_BIND_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_DSLITE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_DSLITE_VAL);
#endif

CompileOption_Val TCSUPPORT_TC2031_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TC2031_VAL);
#endif

CompileOption_Val TCSUPPORT_HWNAT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_HWNAT_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_QOS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_QOS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_1FXS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_1FXS_VAL);
#endif

CompileOption_Val TCSUPPORT_2PORTS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_2PORTS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_C7_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_C7_VAL);
#endif

CompileOption_Val TCSUPPORT_USBHOST_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_USBHOST_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_STANDARD_E8C_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_STANDARD_E8C_VAL);
#endif

CompileOption_Val TCSUPPORT_IPV6_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_IPV6_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_RT3390_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_RT3390_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_RT3090_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_RT3090_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_RT5392_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_RT5392_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_MULTIDRIVER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_MULTIDRIVER_VAL);
#endif

CompileOption_Val TCSUPPORT_WLAN_MT7592_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WLAN_MT7592_VAL);
#endif

CompileOption_Val TCSUPPORT_OMCI_ALCATEL_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_OMCI_ALCATEL_VAL);
#endif

CompileOption_Val TCSUPPORT_GPON_MAPPING_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_GPON_MAPPING_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_USER_ISOLATION_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_USER_ISOLATION_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_VLAN_FILTER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_VLAN_FILTER_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_MAC_FILTER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_MAC_FILTER_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_IGMP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_IGMP_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_VLAN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_VLAN_VAL);
#endif

CompileOption_Val TCSUPPORT_OMCI_LAN_DEBUG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_OMCI_LAN_DEBUG_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_LED_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_LED_VAL);
#endif

CompileOption_Val TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL);
#endif

CompileOption_Val TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL);
#endif

CompileOption_Val TCSUPPORT_IGMP_SET_GROUP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_IGMP_SET_GROUP_VAL);
#endif

CompileOption_Val TCSUPPORT_CD_WIND_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CD_WIND_VAL);
#endif

CompileOption_Val TCSUPPORT_ARC_CWMP_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ARC_CWMP_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_BUTTONDETECT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_BUTTONDETECT_VAL);
#endif

CompileOption_Val TCSUPPORT_ECN_SIP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ECN_SIP_VAL);
#endif

CompileOption_Val TCSUPPORT_ECN_MEGACO_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_ECN_MEGACO_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_VOIP_SIP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_VOIP_SIP_VAL);
#endif

CompileOption_Val TCSUPPORT_CHS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CHS_VAL);
#endif

CompileOption_Val TCSUPPORT_VOIP_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VOIP_VAL);
#endif

CompileOption_Val TCSUPPORT_SLIC_ZL88801_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_SLIC_ZL88801_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_JX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_JX_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_HAL_API_QOS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_HAL_API_QOS_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_HAL_API_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_HAL_API_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_HAL_API_EXT_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_HAL_API_EXT_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_PON_QOS_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_PON_QOS_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_STBMAC_REPORT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_STBMAC_REPORT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PMINFORM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PMINFORM_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_HUB_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_HUB_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ADSL_HN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ADSL_HN_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_SC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_SC_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_C9_HUN_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_C9_HUN_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL);
#endif

CompileOption_Val TCSUPPORT_TR143_CURL_UPLOAD_VAL = 0; 
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_TR143_CURL_UPLOAD_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ADSL_TJ_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ADSL_TJ_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_ADSL_BIND1_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ADSL_BIND1_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_NAMECHGNOTIFY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_NAMECHGNOTIFY_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_C5_HEN_SFU_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_C5_HEN_SFU_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_SFU_SX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_SFU_SX_VAL);
#endif

CompileOption_Val TCSUPPORT_EPON_DUMMY_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_EPON_DUMMY_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_HWNAT_OFFLOAD_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_HWNAT_OFFLOAD_VAL);
#endif

CompileOption_Val TCSUPPORT_DS_HWNAT_OFFLOAD_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_DS_HWNAT_OFFLOAD_VAL);
#endif

/* fix bug OSBNB00044996 by johnson.sun on 20150410 */
CompileOption_Val TCSUPPORT_CT_PON_SK_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_SK_VAL);
#endif

CompileOption_Val TCSUPPORT_CMCC_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CMCC_VAL);
#endif

CompileOption_Val TCSUPPORT_CMCC_GANSU_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CMCC_GANSU_VAL);
#endif


CompileOption_Val TCSUPPORT_CT_ITMS_TMOUT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_ITMS_TMOUT_VAL);
#endif

CompileOption_Val TCSUPPORT_DLF_CTRL_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_DLF_CTRL_VAL);
#endif

CompileOption_Val TCSUPPORT_CPU_PERFORMANCE_TEST_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CPU_PERFORMANCE_TEST_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_IGMP_CHT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_IGMP_CHT_VAL);
#endif

CompileOption_Val TCSUPPORT_WAN_UPSTREAM_REMARK_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_WAN_UPSTREAM_REMARK_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_HAL_API_MCST_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_HAL_API_MCST_VAL);
#endif

CompileOption_Val TCSUPPORT_CPU_EN75XX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CPU_EN75XX_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_JOYME_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_JOYME_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_JOYME_BANDWIDTH_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_JOYME_BANDWIDTH_VAL);
#endif

CompileOption_Val TCSUPPORT_C9_ROST_LED_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_C9_ROST_LED_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL);
#endif

CompileOption_Val TCSUPPORT_UPGRADE_NO_REBOOT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_UPGRADE_NO_REBOOT_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CN_JS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CN_JS_VAL);
#endif

CompileOption_Val TCSUPPORT_CUC_PON_SD_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CUC_PON_SD_VAL);
#endif

CompileOption_Val TCSUPPORT_PON_ROSTELECOM_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_PON_ROSTELECOM_VAL);
#endif

CompileOption_Val TCSUPPORT_XPON_LED_UPGRADE_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_XPON_LED_UPGRADE_VAL);
#endif

CompileOption_Val TCSUPPORT_FWC_ENV_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FWC_ENV_VAL);
#endif

CompileOption_Val TCSUPPORT_FWC_QOS_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FWC_QOS_VAL);
#endif

CompileOption_Val TCSUPPORT_FWC_MCST_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FWC_MCST_VAL);
#endif

CompileOption_Val TCSUPPORT_FWC_FDB_VLAN_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FWC_FDB_VLAN_VAL);
#endif

CompileOption_Val TCSUPPORT_FWC_VLAN_TAG_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_FWC_VLAN_TAG_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CZ_GD_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CZ_GD_VAL);
#endif

CompileOption_Val TCSUPPORT_CT_PON_CZ_NX_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_CT_PON_CZ_NX_VAL);
#endif

CompileOption_Val TCSUPPORT_VNPTT_VAL = 0;
#ifdef __KERNEL__
EXPORT_SYMBOL(TCSUPPORT_VNPTT_VAL);
#endif

void
init_compileoption_val(void){

#ifdef TCSUPPORT_CT
	TCSUPPORT_CT_VAL = 1;
#else
	TCSUPPORT_CT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_VLAN_TAG
	TCSUPPORT_CT_VLAN_TAG_VAL = 1;
#else
	TCSUPPORT_CT_VLAN_TAG_VAL = 0;
#endif

#ifdef TCSUPPORT_VLAN_TAG
	TCSUPPORT_VLAN_TAG_VAL = 1;
#else
	TCSUPPORT_VLAN_TAG_VAL = 0;
#endif

#ifdef TCSUPPORT_TCAPI_ENHANCE
	TCSUPPORT_TCAPI_ENHANCE_VAL = 1;
#else
	TCSUPPORT_TCAPI_ENHANCE_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC_C5_2P
	TCSUPPORT_CUC_C5_2P_VAL = 1;
#else
	TCSUPPORT_CUC_C5_2P_VAL = 0;
#endif

#if 0 
#ifdef TCSUPPORT_CDS_VTAG_TRANSPARENT
	TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 1;
#else
	TCSUPPORT_CDS_VTAG_TRANSPARENT_VAL = 0;
#endif
#endif

#ifdef TCSUPPORT_CT_PON_GD
	TCSUPPORT_CT_PON_GD_VAL = 1;
#else
	TCSUPPORT_CT_PON_GD_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_GDV20
	TCSUPPORT_CT_PON_GDV20_VAL = 1;
#else
	TCSUPPORT_CT_PON_GDV20_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_GDCS
	TCSUPPORT_CT_PON_CZ_GDCS_VAL = 1;
#else
	TCSUPPORT_CT_PON_CZ_GDCS_VAL = 0;
#endif


#ifdef TCSUPPORT_CT_PON_CY
	TCSUPPORT_CT_PON_CY_VAL = 1;
#else
	TCSUPPORT_CT_PON_CY_VAL = 0;
#endif

#ifdef TCSUPPORT_ZARLINK_LE89156A
	TCSUPPORT_ZARLINK_LE89156A_VAL = 1;
#else
	TCSUPPORT_ZARLINK_LE89156A_VAL = 0;
#endif

#ifdef TCSUPPORT_ZARLINK_LE89156B
	TCSUPPORT_ZARLINK_LE89156B_VAL = 1;
#else
	TCSUPPORT_ZARLINK_LE89156B_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CY_JX
	TCSUPPORT_CT_PON_CY_JX_VAL = 1;
#else
	TCSUPPORT_CT_PON_CY_JX_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_BIND2
	TCSUPPORT_CT_PON_BIND2_VAL = 1;
#else
	TCSUPPORT_CT_PON_BIND2_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON
	TCSUPPORT_CT_PON_VAL = 1;
#else
	TCSUPPORT_CT_PON_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_JS
	TCSUPPORT_CT_PON_JS_VAL = 1;
#else
	TCSUPPORT_CT_PON_JS_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_FJ
	TCSUPPORT_CT_FJ_VAL = 1;
#else
	TCSUPPORT_CT_FJ_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_GX
	TCSUPPORT_CT_PON_GX_VAL = 1;
#else
	TCSUPPORT_CT_PON_GX_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CQ
	TCSUPPORT_CT_PON_CQ_VAL = 1;
#else
	TCSUPPORT_CT_PON_CQ_VAL = 0;
#endif


#ifdef TCSUPPORT_CT_UPG_PINGPONG
	TCSUPPORT_CT_UPG_PINGPONG_VAL = 1;
#else
	TCSUPPORT_CT_UPG_PINGPONG_VAL = 0;
#endif

#ifdef TCSUPPORT_BACKUPROMFILE
	TCSUPPORT_BACKUPROMFILE_VAL = 1;
#else
	TCSUPPORT_BACKUPROMFILE_VAL = 0;
#endif

#ifdef TCSUPPORT_PRODUCTIONLINE
	TCSUPPORT_PRODUCTIONLINE_VAL = 1;
#else
	TCSUPPORT_PRODUCTIONLINE_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC_CWMP_PARAMETER
	TCSUPPORT_CUC_CWMP_PARAMETER_VAL = 1;
#else
	TCSUPPORT_CUC_CWMP_PARAMETER_VAL = 0;
#endif

#ifdef TCSUPPORT_NOTDEFAULTROMFILEAREA
	TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL = 1;
#else
	TCSUPPORT_NOTDEFAULTROMFILEAREA_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_MIDWARE
	TCSUPPORT_CT_MIDWARE_VAL = 1;
#else
	TCSUPPORT_CT_MIDWARE_VAL = 0;
#endif

#ifdef TCSUPPORT_CDS
	TCSUPPORT_CDS_VAL = 1;
#else
	TCSUPPORT_CDS_VAL = 0;
#endif

#ifdef TCSUPPORT_VLAN_DOT1P
	TCSUPPORT_VLAN_DOT1P_VAL = 1;
#else
	TCSUPPORT_VLAN_DOT1P_VAL = 0;
#endif

#ifdef TCSUPPORT_VLAN_PASSTHROUGH
	TCSUPPORT_VLAN_PASSTHROUGH_VAL = 1;
#else
	TCSUPPORT_VLAN_PASSTHROUGH_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC_FJ_SFU
	TCSUPPORT_CUC_FJ_SFU_VAL = 1;
#else
	TCSUPPORT_CUC_FJ_SFU_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT
	TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL = 1;
#else
	TCSUPPORT_CT_BACKUPROMFILEENCHANCEMENT_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC
	TCSUPPORT_CUC_VAL = 1;
#else
	TCSUPPORT_CUC_VAL = 0;
#endif

#ifdef TCSUPPORT_CY_PON
	TCSUPPORT_CY_PON_VAL = 1;
#else
	TCSUPPORT_CY_PON_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PHONEAPP
	TCSUPPORT_CT_PHONEAPP_VAL = 1;
#else
	TCSUPPORT_CT_PHONEAPP_VAL = 0;
#endif

#ifdef TCSUPPORT_AUTOBENCH
	TCSUPPORT_AUTOBENCH_VAL = 1;
#else
	TCSUPPORT_AUTOBENCH_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_C9
	TCSUPPORT_CT_PON_C9_VAL = 1;
#else
	TCSUPPORT_CT_PON_C9_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_JS_IP
	TCSUPPORT_CT_PON_JS_IP_VAL = 1;
#else
	TCSUPPORT_CT_PON_JS_IP_VAL = 0;
#endif

#ifdef TCSUPPORT_VOIP_LED_APPCTRL
	TCSUPPORT_VOIP_LED_APPCTRL_VAL = 1;
#else
	TCSUPPORT_VOIP_LED_APPCTRL_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_VOIP_CRYPT
	TCSUPPORT_CT_VOIP_CRYPT_VAL = 1;
#else
	TCSUPPORT_CT_VOIP_CRYPT_VAL = 0;
#endif

#ifdef TCSUPPORT_PON_FH
	TCSUPPORT_PON_FH_VAL = 1;
#else
	TCSUPPORT_PON_FH_VAL = 0;
#endif

#ifdef TCSUPPORT_VOIP_SIP_DNS
	TCSUPPORT_VOIP_SIP_DNS_VAL = 1;
#else
	TCSUPPORT_VOIP_SIP_DNS_VAL = 0;
#endif

#ifdef TCSUPPORT_C1_MS
	TCSUPPORT_C1_MS_VAL = 1;
#else
	TCSUPPORT_C1_MS_VAL = 0;
#endif

#ifdef TCSUPPORT_C1_ZY
	TCSUPPORT_C1_ZY_VAL = 1;
#else
	TCSUPPORT_C1_ZY_VAL = 0;
#endif

#ifdef TCSUPPORT_PONMGR
	TCSUPPORT_PONMGR_VAL = 1;
#else
	TCSUPPORT_PONMGR_VAL = 0;
#endif


#ifdef TCSUPPORT_PMMGR
	TCSUPPORT_PMMGR_VAL = 1;
#else
	TCSUPPORT_PMMGR_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_ATM
	TCSUPPORT_WAN_ATM_VAL = 1;
#else
	TCSUPPORT_WAN_ATM_VAL = 0;
#endif

#ifdef TCSUPPORT_CPU_MT7505
	TCSUPPORT_CPU_MT7505_VAL = 1;
#else
	TCSUPPORT_CPU_MT7505_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_YN
	TCSUPPORT_CT_PON_YN_VAL = 1;
#else
	TCSUPPORT_CT_PON_YN_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_DEV_ACCESS_TYPE
	TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL = 1;
#else
	TCSUPPORT_CT_DEV_ACCESS_TYPE_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ECN_GZ
	TCSUPPORT_CT_ECN_GZ_VAL = 1;
#else
	TCSUPPORT_CT_ECN_GZ_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_WANNINDEX_INCREASE
	TCSUPPORT_CT_WANNINDEX_INCREASE_VAL = 1;
#else
	TCSUPPORT_CT_WANNINDEX_INCREASE_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_MONITORCOLLECTOR
	TCSUPPORT_CT_MONITORCOLLECTOR_VAL = 1;
#else
	TCSUPPORT_CT_MONITORCOLLECTOR_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PPPOE_EMULATOR
	TCSUPPORT_CT_PPPOE_EMULATOR_VAL = 1;
#else
	TCSUPPORT_CT_PPPOE_EMULATOR_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_NMG
	TCSUPPORT_CT_PON_NMG_VAL = 1;
#else
	TCSUPPORT_CT_PON_NMG_VAL = 0;
#endif

#ifdef TCSUPPORT_CY_E8_SFU
	TCSUPPORT_CY_E8_SFU_VAL = 1;
#else
	TCSUPPORT_CY_E8_SFU_VAL = 0;
#endif

#ifdef TCSUPPORT_ITMS_CONFIG_AS_DEFAULT
	TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL = 1;
#else
	TCSUPPORT_ITMS_CONFIG_AS_DEFAULT_VAL = 0;
#endif
#ifdef CT_COM_DEVICEREG
	CT_COM_DEVICEREG_VAL = 1;
#else
	CT_COM_DEVICEREG_VAL = 0;
#endif

#ifdef TCSUPPORT_DMS
	TCSUPPORT_DMS_VAL = 1;
#else
	TCSUPPORT_DMS_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_UPNP_DM
	TCSUPPORT_CT_UPNP_DM_VAL = 1;
#else
	TCSUPPORT_CT_UPNP_DM_VAL = 0;
#endif

#ifdef TCSUPPORT_TR69_IP_HOST
	TCSUPPORT_TR69_IP_HOST_VAL = 1;
#else
	TCSUPPORT_TR69_IP_HOST_VAL = 0;
#endif

#ifdef TCSUPPORT_PON_IP_HOST
	TCSUPPORT_PON_IP_HOST_VAL = 1;
#else
	TCSUPPORT_PON_IP_HOST_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PPPINFORM
	TCSUPPORT_CT_PPPINFORM_VAL = 1;
#else
	TCSUPPORT_CT_PPPINFORM_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_SWQOS
	TCSUPPORT_CT_SWQOS_VAL = 1;
#else
	TCSUPPORT_CT_SWQOS_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_SIMCARD_SEPARATION
	TCSUPPORT_CT_SIMCARD_SEPARATION_VAL = 1;
#else
	TCSUPPORT_CT_SIMCARD_SEPARATION_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_2PORTS
	TCSUPPORT_CT_2PORTS_VAL = 1;
#else
	TCSUPPORT_CT_2PORTS_VAL = 0;
#endif

#ifdef TCSUPPORT_LAN_VLAN
	TCSUPPORT_LAN_VLAN_VAL = 1;
#else
	TCSUPPORT_LAN_VLAN_VAL = 0;
#endif

#ifdef TCSUPPORT_LAN_VLAN_RANGE
	TCSUPPORT_LAN_VLAN_RANGE_VAL = 1;
#else
	TCSUPPORT_LAN_VLAN_RANGE_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_SN
	TCSUPPORT_CT_PON_SN_VAL = 1;
#else
	TCSUPPORT_CT_PON_SN_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_WAN_PTM
	TCSUPPORT_CT_WAN_PTM_VAL = 1;
#else
	TCSUPPORT_CT_WAN_PTM_VAL = 0;
#endif

#ifdef TCSUPPORT_C1_CUC
	TCSUPPORT_C1_CUC_VAL = 1;
#else
	TCSUPPORT_C1_CUC_VAL = 0;
#endif

#ifdef TCSUPPORT_SYSLOG
	TCSUPPORT_SYSLOG_VAL = 1;
#else
	TCSUPPORT_SYSLOG_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PORT_BIND
	TCSUPPORT_CT_PORT_BIND_VAL = 1;
#else
	TCSUPPORT_CT_PORT_BIND_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_GUIACCESSLIMIT
	TCSUPPORT_CT_GUIACCESSLIMIT_VAL = 1;
#else
	TCSUPPORT_CT_GUIACCESSLIMIT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PPPOEPROXY
	TCSUPPORT_CT_PPPOEPROXY_VAL = 1;
#else
	TCSUPPORT_CT_PPPOEPROXY_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ZIPROMFILE
	TCSUPPORT_CT_ZIPROMFILE_VAL = 1;
#else
	TCSUPPORT_CT_ZIPROMFILE_VAL = 0;
#endif

#ifdef TCSUPPORT_RESERVEAREA_EXTEND
	TCSUPPORT_RESERVEAREA_EXTEND_VAL = 1;
#else
	TCSUPPORT_RESERVEAREA_EXTEND_VAL = 0;
#endif

#ifdef TCSUPPORT_C7
	TCSUPPORT_C7_VAL = 1;
#else
	TCSUPPORT_C7_VAL = 0;
#endif

#ifdef TCSUPPORT_CY
	TCSUPPORT_CY_VAL = 1;
#else
	TCSUPPORT_CY_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_E8B_ADSL
	TCSUPPORT_CT_E8B_ADSL_VAL = 1;
#else
	TCSUPPORT_CT_E8B_ADSL_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_WANNODE_MAPPING
	TCSUPPORT_CT_WANNODE_MAPPING_VAL = 1;
#else
	TCSUPPORT_CT_WANNODE_MAPPING_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_BLOCK_PROCESS
	TCSUPPORT_CT_BLOCK_PROCESS_VAL = 1;
#else
	TCSUPPORT_CT_BLOCK_PROCESS_VAL = 0;
#endif

#ifdef TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND
	TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL = 1;
#else
	TCSUPPORT_ROUTEPOLICY_PRIOR_PORTBIND_VAL = 0;
#endif

#ifdef TCSUPPORT_CPU_MT7510
	TCSUPPORT_CPU_MT7510_VAL = 1;
#else
	TCSUPPORT_CPU_MT7510_VAL = 0;
#endif

#ifdef TCSUPPORT_CPU_MT7520
	TCSUPPORT_CPU_MT7520_VAL = 1;
#else
	TCSUPPORT_CPU_MT7520_VAL = 0;
#endif

#ifdef TCSUPPORT_TRUE_LANDING_PAGE
	TCSUPPORT_TRUE_LANDING_PAGE_VAL = 1;
#else
	TCSUPPORT_TRUE_LANDING_PAGE_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP
	TCSUPPORT_CWMP_VAL = 1;
#else
	TCSUPPORT_CWMP_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_NO_HOST
	TCSUPPORT_CWMP_NO_HOST_VAL = 1;
#else
	TCSUPPORT_CWMP_NO_HOST_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN
	TCSUPPORT_WLAN_VAL = 1;
#else
	TCSUPPORT_WLAN_VAL = 0;
#endif

#ifdef TCSUPPORT_INIC_CLIENT
	TCSUPPORT_INIC_CLIENT_VAL = 1;
#else
	TCSUPPORT_INIC_CLIENT_VAL = 0;
#endif

#ifdef TCSUPPORT_CZ_GENERAL
	TCSUPPORT_CZ_GENERAL_VAL = 1;
#else
	TCSUPPORT_CZ_GENERAL_VAL = 0;
#endif

#ifdef TCSUPPORT_KEYPARA_STORE
	TCSUPPORT_KEYPARA_STORE_VAL = 1;
#else
	TCSUPPORT_KEYPARA_STORE_VAL = 0;
#endif

#ifdef TCSUPPORT_VPN
	TCSUPPORT_VPN_VAL = 1;
#else
	TCSUPPORT_VPN_VAL = 0;
#endif

#ifdef TCSUPPORT_MULTI_BOOT
	TCSUPPORT_MULTI_BOOT_VAL = 1;
#else
	TCSUPPORT_MULTI_BOOT_VAL = 0;
#endif

#ifdef TCSUPPORT_START_TRAP
	TCSUPPORT_START_TRAP_VAL = 1;
#else
	TCSUPPORT_START_TRAP_VAL = 0;
#endif

#ifdef TCSUPPORT_SYSLOG_ENHANCE
	TCSUPPORT_SYSLOG_ENHANCE_VAL = 1;
#else
	TCSUPPORT_SYSLOG_ENHANCE_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_AC
	TCSUPPORT_WLAN_AC_VAL = 1;
#else
	TCSUPPORT_WLAN_AC_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_FAST_GET
	TCSUPPORT_CWMP_FAST_GET_VAL = 1;
#else
	TCSUPPORT_CWMP_FAST_GET_VAL = 0;
#endif

#ifdef TCSUPPORT_CD_DDNS
	TCSUPPORT_CD_DDNS_VAL = 1;
#else
	TCSUPPORT_CD_DDNS_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_GPON
	TCSUPPORT_WAN_GPON_VAL = 1;
#else
	TCSUPPORT_WAN_GPON_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_EPON
	TCSUPPORT_WAN_EPON_VAL = 1;
#else
	TCSUPPORT_WAN_EPON_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_ETHER
	TCSUPPORT_WAN_ETHER_VAL = 1;
#else
	TCSUPPORT_WAN_ETHER_VAL = 0;
#endif

#ifdef TCSUPPORT_OMCI
	TCSUPPORT_OMCI_VAL = 1;
#else
	TCSUPPORT_OMCI_VAL = 0;
#endif

#ifdef TCSUPPORT_EPON_OAM_CTC
	TCSUPPORT_EPON_OAM_CTC_VAL = 1;
#else
	TCSUPPORT_EPON_OAM_CTC_VAL = 0;
#endif

#ifdef TCSUPPORT_CMDPROMPT
	TCSUPPORT_CMDPROMPT_VAL = 1;
#else
	TCSUPPORT_CMDPROMPT_VAL = 0;
#endif

#ifdef TCSUPPORT_RANDOM_INFORM
	TCSUPPORT_RANDOM_INFORM_VAL = 1;
#else
	TCSUPPORT_RANDOM_INFORM_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_SERVICELIST_E8C
	TCSUPPORT_CT_SERVICELIST_E8C_VAL = 1;
#else
	TCSUPPORT_CT_SERVICELIST_E8C_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ALARMMONITOR
	TCSUPPORT_CT_ALARMMONITOR_VAL = 1;
#else
	TCSUPPORT_CT_ALARMMONITOR_VAL = 0;
#endif

#ifdef TCSUPPORT_CZ_TM
	TCSUPPORT_CZ_TM_VAL = 1;
#else
	TCSUPPORT_CZ_TM_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_INFORM_NODE
	TCSUPPORT_CT_INFORM_NODE_VAL = 1;
#else
	TCSUPPORT_CT_INFORM_NODE_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_LONG_RESETBTN
	TCSUPPORT_CT_LONG_RESETBTN_VAL = 1;
#else
	TCSUPPORT_CT_LONG_RESETBTN_VAL = 0;
#endif

#ifdef CWMP_REDIRECT
	CWMP_REDIRECT_VAL = 1;
#else
	CWMP_REDIRECT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PPP_ONDEMAND
	TCSUPPORT_CT_PPP_ONDEMAND_VAL = 1;
#else
	TCSUPPORT_CT_PPP_ONDEMAND_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_CWMP_ZIPROMFILE
	TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL = 1;
#else
	TCSUPPORT_CT_CWMP_ZIPROMFILE_VAL = 0;
#endif

#ifdef TCSUPPORT_TR69_BIND_PVC
	TCSUPPORT_TR69_BIND_PVC_VAL = 1;
#else
	TCSUPPORT_TR69_BIND_PVC_VAL = 0;
#endif

#ifdef TCSUPPORT_NO_BOOT_VALUECHANGE
	TCSUPPORT_NO_BOOT_VALUECHANGE_VAL = 1;
#else
	TCSUPPORT_NO_BOOT_VALUECHANGE_VAL = 0;
#endif

#ifdef TCSUPPORT_CROSS_REBOOT
	TCSUPPORT_CROSS_REBOOT_VAL = 1;
#else
	TCSUPPORT_CROSS_REBOOT_VAL = 0;
#endif

#ifdef TCSUPPORT_BHARTI
	TCSUPPORT_BHARTI_VAL = 1;
#else
	TCSUPPORT_BHARTI_VAL = 0;
#endif

#ifdef TCSUPPORT_TTNET
	TCSUPPORT_TTNET_VAL = 1;
#else
	TCSUPPORT_TTNET_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_PRECISE_TIME
	TCSUPPORT_CWMP_PRECISE_TIME_VAL = 1;
#else
	TCSUPPORT_CWMP_PRECISE_TIME_VAL = 0;
#endif

#ifdef TCSUPPORT_C1_NEW_GUI
	TCSUPPORT_C1_NEW_GUI_VAL = 1;
#else
	TCSUPPORT_C1_NEW_GUI_VAL = 0;
#endif

#ifdef TCSUPPORT_PROLINE_CMD_ACTION
	TCSUPPORT_PROLINE_CMD_ACTION_VAL = 1;
#else
	TCSUPPORT_PROLINE_CMD_ACTION_VAL = 0;
#endif

#ifdef TCSUPPORT_MULTISERVICE_ON_WAN
	TCSUPPORT_MULTISERVICE_ON_WAN_VAL = 1;
#else
	TCSUPPORT_MULTISERVICE_ON_WAN_VAL = 0;
#endif

#ifdef TCSUPPORT_UPNP_ENHANCE
	TCSUPPORT_UPNP_ENHANCE_VAL = 1;
#else
	TCSUPPORT_UPNP_ENHANCE_VAL = 0;
#endif

#ifdef TCSUPPORT_C1_OBM
	TCSUPPORT_C1_OBM_VAL = 1;
#else
	TCSUPPORT_C1_OBM_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_PTM
	TCSUPPORT_WAN_PTM_VAL = 1;
#else
	TCSUPPORT_WAN_PTM_VAL = 0;
#endif

#ifdef TCSUPPORT_CD_NEW_GUI
	TCSUPPORT_CD_NEW_GUI_VAL = 1;
#else
	TCSUPPORT_CD_NEW_GUI_VAL = 0;
#endif

#ifdef TCSUPPORT_CCT
	TCSUPPORT_CCT_VAL = 1;
#else
	TCSUPPORT_CCT_VAL = 0;
#endif

#ifdef TCSUPPORT_CLMP
	TCSUPPORT_CLMP_VAL = 1;
#else
	TCSUPPORT_CLMP_VAL = 0;
#endif

#ifdef TCSUPPORT_SAGECOM_CWMP
	TCSUPPORT_SAGECOM_CWMP_VAL = 1;
#else
	TCSUPPORT_SAGECOM_CWMP_VAL = 0;
#endif

#ifdef TCSUPPORT_FW_UPGRADE_DELAY
	TCSUPPORT_FW_UPGRADE_DELAY_VAL = 1;
#else
	TCSUPPORT_FW_UPGRADE_DELAY_VAL = 0;
#endif

#ifdef AZTECH_CWMP_REORDER
	AZTECH_CWMP_REORDER_VAL = 1;
#else
	AZTECH_CWMP_REORDER_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_IOT_STRINGTYPE
	TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL = 1;
#else
	TCSUPPORT_CWMP_IOT_STRINGTYPE_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_FAULT_RESPONSE
	TCSUPPORT_CWMP_FAULT_RESPONSE_VAL = 1;
#else
	TCSUPPORT_CWMP_FAULT_RESPONSE_VAL = 0;
#endif

#ifdef TCSUPPORT_CWMP_CRPORTCHANGE
	TCSUPPORT_CWMP_CRPORTCHANGE_VAL = 1;
#else
	TCSUPPORT_CWMP_CRPORTCHANGE_VAL = 0;
#endif

#ifdef TCSUPPORT_WEB_INTERCEPTION
	TCSUPPORT_WEB_INTERCEPTION_VAL = 1;
#else
	TCSUPPORT_WEB_INTERCEPTION_VAL = 0;
#endif

#ifdef TCSUPPORT_MNT_CONF
	TCSUPPORT_MNT_CONF_VAL = 1;
#else
	TCSUPPORT_MNT_CONF_VAL = 0;
#endif

#ifdef TCSUPPORT_FTP_USB
	TCSUPPORT_FTP_USB_VAL = 1;
#else
	TCSUPPORT_FTP_USB_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_FTP_DOWNLOADCLIENT
	TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL = 1;
#else
	TCSUPPORT_CT_FTP_DOWNLOADCLIENT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_NEWGUI
	TCSUPPORT_CT_NEWGUI_VAL = 1;
#else
	TCSUPPORT_CT_NEWGUI_VAL = 0;
#endif

#ifdef TCSUPPORT_IPV6_FIREWALL
	TCSUPPORT_IPV6_FIREWALL_VAL = 1;
#else
	TCSUPPORT_IPV6_FIREWALL_VAL = 0;
#endif

#ifdef TCSUPPORT_IPV6_FIREWALL_RFC2827
	TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL = 1;
#else
	TCSUPPORT_IPV6_FIREWALL_RFC2827_VAL = 0;
#endif

#ifdef TCSUPPORT_PRODUCTIONLINE_CONTENT
	TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL = 1;
#else
	TCSUPPORT_PRODUCTIONLINE_CONTENT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_HWQOS
	TCSUPPORT_CT_HWQOS_VAL = 1;
#else
	TCSUPPORT_CT_HWQOS_VAL = 0;
#endif

#ifdef TCSUPPORT_CHT_RAMENU
	TCSUPPORT_CHT_RAMENU_VAL = 1;
#else
	TCSUPPORT_CHT_RAMENU_VAL = 0;
#endif

#ifdef TCSUPPORT_EPON_OAM_LAN_DBG
	TCSUPPORT_EPON_OAM_LAN_DBG_VAL = 1;
#else
	TCSUPPORT_EPON_OAM_LAN_DBG_VAL = 0;
#endif

#ifdef TCSUPPORT_E8B
	TCSUPPORT_E8B_VAL = 1;
#else
	TCSUPPORT_E8B_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_VLAN_BIND
	TCSUPPORT_CT_VLAN_BIND_VAL = 1;
#else
	TCSUPPORT_CT_VLAN_BIND_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_DSLITE
	TCSUPPORT_CT_DSLITE_VAL = 1;
#else
	TCSUPPORT_CT_DSLITE_VAL = 0;
#endif

#ifdef TCSUPPORT_TC2031
	TCSUPPORT_TC2031_VAL = 1;
#else
	TCSUPPORT_TC2031_VAL = 0;
#endif

#ifdef TCSUPPORT_HWNAT
	TCSUPPORT_HWNAT_VAL = 1;
#else
	TCSUPPORT_HWNAT_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC_QOS
	TCSUPPORT_CUC_QOS_VAL = 1;
#else
	TCSUPPORT_CUC_QOS_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_1FXS
	TCSUPPORT_CT_1FXS_VAL = 1;
#else
	TCSUPPORT_CT_1FXS_VAL = 0;
#endif

#ifdef TCSUPPORT_2PORTS
	TCSUPPORT_2PORTS_VAL = 1;
#else
	TCSUPPORT_2PORTS_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_C7
	TCSUPPORT_CT_PON_C7_VAL = 1;
#else
	TCSUPPORT_CT_PON_C7_VAL = 0;
#endif

#ifdef TCSUPPORT_USBHOST
	TCSUPPORT_USBHOST_VAL = 1;
#else
	TCSUPPORT_USBHOST_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_STANDARD_E8C
	TCSUPPORT_CT_STANDARD_E8C_VAL = 1;
#else
	TCSUPPORT_CT_STANDARD_E8C_VAL = 0;
#endif

#ifdef TCSUPPORT_IPV6
	TCSUPPORT_IPV6_VAL = 1;
#else
	TCSUPPORT_IPV6_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_RT3390
	TCSUPPORT_WLAN_RT3390_VAL = 1;
#else
	TCSUPPORT_WLAN_RT3390_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_RT3090
	TCSUPPORT_WLAN_RT3090_VAL = 1;
#else
	TCSUPPORT_WLAN_RT3090_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_RT5392
	TCSUPPORT_WLAN_RT5392_VAL = 1;
#else
	TCSUPPORT_WLAN_RT5392_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_MULTIDRIVER
	TCSUPPORT_WLAN_MULTIDRIVER_VAL = 1;
#else
	TCSUPPORT_WLAN_MULTIDRIVER_VAL = 0;
#endif

#ifdef TCSUPPORT_WLAN_MT7592
	TCSUPPORT_WLAN_MT7592_VAL = 1;
#else
	TCSUPPORT_WLAN_MT7592_VAL = 0;
#endif

#ifdef TCSUPPORT_OMCI_ALCATEL
	TCSUPPORT_OMCI_ALCATEL_VAL = 1;
#else
	TCSUPPORT_OMCI_ALCATEL_VAL = 0;
#endif

#ifdef TCSUPPORT_GPON_MAPPING
	TCSUPPORT_GPON_MAPPING_VAL = 1;
#else
	TCSUPPORT_GPON_MAPPING_VAL = 0;
#endif

#if defined(TCSUPPORT_XPON_HAL_API_QOS) 
		TCSUPPORT_XPON_HAL_API_QOS_VAL=1;
#else
		TCSUPPORT_XPON_HAL_API_QOS_VAL=0;
#endif

#if defined(TCSUPPORT_XPON_HAL_API) 
		TCSUPPORT_XPON_HAL_API_VAL=1;
#else
		TCSUPPORT_XPON_HAL_API_VAL=0;
#endif

#if defined(TCSUPPORT_XPON_HAL_API_EXT)
		TCSUPPORT_XPON_HAL_API_EXT_VAL=1;
#else
		TCSUPPORT_XPON_HAL_API_EXT_VAL=0;
#endif


#ifdef TCSUPPORT_PON_USER_ISOLATION
	TCSUPPORT_PON_USER_ISOLATION_VAL = 1;
#else
	TCSUPPORT_PON_USER_ISOLATION_VAL = 0;
#endif

#ifdef TCSUPPORT_PON_VLAN_FILTER
	TCSUPPORT_PON_VLAN_FILTER_VAL = 1;
#else
	TCSUPPORT_PON_VLAN_FILTER_VAL = 0;
#endif

#ifdef TCSUPPORT_PON_MAC_FILTER
	TCSUPPORT_PON_MAC_FILTER_VAL = 1;
#else
	TCSUPPORT_PON_MAC_FILTER_VAL = 0;
#endif

#ifdef TCSUPPORT_XPON_IGMP
	TCSUPPORT_XPON_IGMP_VAL = 1;
#else
	TCSUPPORT_XPON_IGMP_VAL = 0;
#endif

#if defined(TCSUPPORT_CT_PON) || defined(TCSUPPORT_XPON_HAL_API_QOS) || defined(TCSUPPORT_XPON_HAL_API_EXT)
		TCSUPPORT_XPON_PON_QOS_VAL=1;
#else
		TCSUPPORT_XPON_PON_QOS_VAL=0;
#endif

#ifdef TCSUPPORT_PON_VLAN
	TCSUPPORT_PON_VLAN_VAL = 1;
#else
	TCSUPPORT_PON_VLAN_VAL = 0;
#endif

#ifdef TCSUPPORT_OMCI_LAN_DEBUG
	TCSUPPORT_OMCI_LAN_DEBUG_VAL = 1;
#else
	TCSUPPORT_OMCI_LAN_DEBUG_VAL = 0;
#endif

#ifdef TCSUPPORT_XPON_LED
	TCSUPPORT_XPON_LED_VAL = 1;
#else
	TCSUPPORT_XPON_LED_VAL = 0;
#endif

#ifdef TCSUPPORT_UPSTREAM_VLAN_POLICER
	TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL = 1;
#else
	TCSUPPORT_UPSTREAM_VLAN_POLICER_VAL = 0;
#endif

#ifdef TCSUPPORT_GPON_DOWNSTREAM_MAPPING
	TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL = 1;
#else
	TCSUPPORT_GPON_DOWNSTREAM_MAPPING_VAL = 0;
#endif

#ifdef TCSUPPORT_IGMP_SET_GROUP
	TCSUPPORT_IGMP_SET_GROUP_VAL = 1;
#else
	TCSUPPORT_IGMP_SET_GROUP_VAL = 0;
#endif

#ifdef TCSUPPORT_CD_WIND
	TCSUPPORT_CD_WIND_VAL = 1;
#else
	TCSUPPORT_CD_WIND_VAL = 0;
#endif

#ifdef TCSUPPORT_ARC_CWMP
	TCSUPPORT_ARC_CWMP_VAL = 1;
#else
	TCSUPPORT_ARC_CWMP_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_BUTTONDETECT
	TCSUPPORT_CT_BUTTONDETECT_VAL = 1;
#else
	TCSUPPORT_CT_BUTTONDETECT_VAL = 0;
#endif

#ifdef TCSUPPORT_ECN_SIP
	TCSUPPORT_ECN_SIP_VAL = 1;
#else
	TCSUPPORT_ECN_SIP_VAL = 0;
#endif

#ifdef TCSUPPORT_ECN_MEGACO
	TCSUPPORT_ECN_MEGACO_VAL = 1;
#else
	TCSUPPORT_ECN_MEGACO_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_VOIP_SIP
	TCSUPPORT_CT_VOIP_SIP_VAL = 1;
#else
	TCSUPPORT_CT_VOIP_SIP_VAL = 0;
#endif

#ifdef TCSUPPORT_CHS
	TCSUPPORT_CHS_VAL = 1;
#else
	TCSUPPORT_CHS_VAL = 0;
#endif

#ifdef TCSUPPORT_VOIP
	TCSUPPORT_VOIP_VAL = 1;
#else
	TCSUPPORT_VOIP_VAL = 0;
#endif

#ifdef TCSUPPORT_SLIC_ZL88801
	TCSUPPORT_SLIC_ZL88801_VAL = 1;
#else
	TCSUPPORT_SLIC_ZL88801_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_JX
	TCSUPPORT_CT_PON_JX_VAL = 1;
#else
	TCSUPPORT_CT_PON_JX_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_STBMAC_REPORT
	TCSUPPORT_CT_STBMAC_REPORT_VAL = 1;
#else
	TCSUPPORT_CT_STBMAC_REPORT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PMINFORM
	TCSUPPORT_CT_PMINFORM_VAL = 1;
#else
	TCSUPPORT_CT_PMINFORM_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_HUB
	TCSUPPORT_CT_PON_HUB_VAL = 1;
#else
	TCSUPPORT_CT_PON_HUB_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_SC
	TCSUPPORT_CT_PON_SC_VAL = 1;
#else
	TCSUPPORT_CT_PON_SC_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ADSL_HN
	TCSUPPORT_CT_ADSL_HN_VAL = 1;
#else
	TCSUPPORT_CT_ADSL_HN_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_C9_HUN
	TCSUPPORT_CT_PON_C9_HUN_VAL = 1;
#else
	TCSUPPORT_CT_PON_C9_HUN_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_TR143_WGET_DOWNLOAD
	TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL = 1;
#else
	TCSUPPORT_CT_TR143_WGET_DOWNLOAD_VAL = 0;
#endif

#ifdef TCSUPPORT_TR143_CURL_UPLOAD
	TCSUPPORT_TR143_CURL_UPLOAD_VAL = 1;
#else
	TCSUPPORT_TR143_CURL_UPLOAD_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ADSL_TJ
	TCSUPPORT_CT_ADSL_TJ_VAL = 1;
#else
	TCSUPPORT_CT_ADSL_TJ_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_ADSL_BIND1
	TCSUPPORT_CT_ADSL_BIND1_VAL = 1;
#else
	TCSUPPORT_CT_ADSL_BIND1_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_NAMECHGNOTIFY
	TCSUPPORT_CT_NAMECHGNOTIFY_VAL = 1;
#else
	TCSUPPORT_CT_NAMECHGNOTIFY_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_C5_HEN_SFU
	TCSUPPORT_CT_C5_HEN_SFU_VAL = 1;
#else
	TCSUPPORT_CT_C5_HEN_SFU_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_SFU_SX
	TCSUPPORT_CT_SFU_SX_VAL = 1;
#else
	TCSUPPORT_CT_SFU_SX_VAL = 0;
#endif

#ifdef TCSUPPORT_EPON_DUMMY
	TCSUPPORT_EPON_DUMMY_VAL = 1;
#else
	TCSUPPORT_EPON_DUMMY_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_HWNAT_OFFLOAD
	TCSUPPORT_CT_HWNAT_OFFLOAD_VAL = 1;
#else
	TCSUPPORT_CT_HWNAT_OFFLOAD_VAL = 0;
#endif

#ifdef TCSUPPORT_DS_HWNAT_OFFLOAD
	TCSUPPORT_DS_HWNAT_OFFLOAD_VAL = 1;
#else
	TCSUPPORT_DS_HWNAT_OFFLOAD_VAL = 0;
#endif

/* fix bug OSBNB00044996 by johnson.sun on 20150410 */
#ifdef TCSUPPORT_CT_PON_SK
	TCSUPPORT_CT_PON_SK_VAL = 1;
#else
	TCSUPPORT_CT_PON_SK_VAL = 0;
#endif

#ifdef TCSUPPORT_CMCC
	TCSUPPORT_CMCC_VAL = 1;
#else
	TCSUPPORT_CMCC_VAL = 0;
#endif

#ifdef TCSUPPORT_CMCC_GANSU
	TCSUPPORT_CMCC_GANSU_VAL = 1;
#else
	TCSUPPORT_CMCC_GANSU_VAL = 0;
#endif


#ifdef TCSUPPORT_CT_ITMS_TMOUT
		TCSUPPORT_CT_ITMS_TMOUT_VAL = 1;
#else
		TCSUPPORT_CT_ITMS_TMOUT_VAL = 0;
#endif

#ifdef TCSUPPORT_CPU_PERFORMANCE_TEST
	TCSUPPORT_CPU_PERFORMANCE_TEST_VAL = 1;
#else
	TCSUPPORT_CPU_PERFORMANCE_TEST_VAL = 0;
#endif

#ifdef TCSUPPORT_XPON_IGMP_CHT
		TCSUPPORT_XPON_IGMP_CHT_VAL = 1;
#else
		TCSUPPORT_XPON_IGMP_CHT_VAL = 0;
#endif

#ifdef TCSUPPORT_WAN_UPSTREAM_REMARK
	TCSUPPORT_WAN_UPSTREAM_REMARK_VAL = 1;
#else
	TCSUPPORT_WAN_UPSTREAM_REMARK_VAL = 0;
#endif

#ifdef TCSUPPORT_XPON_HAL_API_MCST
	TCSUPPORT_XPON_HAL_API_MCST_VAL = 1;
#else
	TCSUPPORT_XPON_HAL_API_MCST_VAL = 0;
#endif
#if defined(TCSUPPORT_CPU_EN7512) || defined(TCSUPPORT_CPU_EN7521)
    TCSUPPORT_CPU_EN75XX_VAL = 1;
#else
    TCSUPPORT_CPU_EN75XX_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_JOYME
	TCSUPPORT_CT_JOYME_VAL = 1;
#else
	TCSUPPORT_CT_JOYME_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_JOYME_BANDWIDTH
		TCSUPPORT_CT_JOYME_BANDWIDTH_VAL = 1;
#else
		TCSUPPORT_CT_JOYME_BANDWIDTH_VAL = 0;
#endif

#ifdef TCSUPPORT_C9_ROST_LED
		TCSUPPORT_C9_ROST_LED_VAL = 1;
#else
		TCSUPPORT_C9_ROST_LED_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_CWMP_WORK_COMPATIBLE
	TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL = 1;
#else
	TCSUPPORT_CT_CWMP_WORK_COMPATIBLE_VAL = 0;
#endif

#ifdef TCSUPPORT_UPGRADE_NO_REBOOT
	TCSUPPORT_UPGRADE_NO_REBOOT_VAL = 1;
#else
	TCSUPPORT_UPGRADE_NO_REBOOT_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CN_JS
	TCSUPPORT_CT_PON_CN_JS_VAL = 1;
#else
	TCSUPPORT_CT_PON_CN_JS_VAL = 0;
#endif

#ifdef TCSUPPORT_CUC_PON_SD
	TCSUPPORT_CUC_PON_SD_VAL = 1;
#else
	TCSUPPORT_CUC_PON_SD_VAL = 0;
#endif

#ifdef TCSUPPORT_PON_ROSTELECOM
        TCSUPPORT_PON_ROSTELECOM_VAL = 1;
#else
        TCSUPPORT_PON_ROSTELECOM_VAL = 0;
#endif

#ifdef TCSUPPORT_XPON_LED_UPGRADE
	TCSUPPORT_XPON_LED_UPGRADE_VAL = 1;
#else
	TCSUPPORT_XPON_LED_UPGRADE_VAL = 0;
#endif

#ifdef TCSUPPORT_FWC_ENV
	TCSUPPORT_FWC_ENV_VAL = 1;
#else
	TCSUPPORT_FWC_ENV_VAL = 0;
#endif

#if defined(TCSUPPORT_PON_VLAN) || defined(TCSUPPORT_PON_MAC_FILTER) || (defined(TCSUPPORT_GPON_MAPPING) && defined(TCSUPPORT_GPON_DOWNSTREAM_MAPPING))
	RA_NAT_EXE_VAL = 1;
#else
	RA_NAT_EXE_VAL = 0;
#endif
	
#ifdef TCSUPPORT_DLF_CTRL
	TCSUPPORT_DLF_CTRL_VAL = 1;
#else
	TCSUPPORT_DLF_CTRL_VAL = 0;
#endif

#ifdef TCSUPPORT_FWC_QOS
	TCSUPPORT_FWC_QOS_VAL = 1;
#else
	TCSUPPORT_FWC_QOS_VAL = 0;
#endif

#ifdef TCSUPPORT_FWC_MCST
	TCSUPPORT_FWC_MCST_VAL = 1;
#else
	TCSUPPORT_FWC_MCST_VAL = 0;
#endif

#ifdef TCSUPPORT_FWC_FDB_VLAN
	TCSUPPORT_FWC_FDB_VLAN_VAL = 1;
#else
	TCSUPPORT_FWC_FDB_VLAN_VAL = 0;
#endif

#ifdef TCSUPPORT_FWC_VLAN_TAG
	TCSUPPORT_FWC_VLAN_TAG_VAL = 1;
#else
	TCSUPPORT_FWC_VLAN_TAG_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_GD
		TCSUPPORT_CT_PON_CZ_GD_VAL = 1;
#else
		TCSUPPORT_CT_PON_CZ_GD_VAL = 0;
#endif

#ifdef TCSUPPORT_CT_PON_CZ_NX
		TCSUPPORT_CT_PON_CZ_NX_VAL = 1;
#else
		TCSUPPORT_CT_PON_CZ_NX_VAL = 0;
#endif

#ifdef TCSUPPORT_VNPTT
		TCSUPPORT_VNPTT_VAL = 1;
#else
		TCSUPPORT_VNPTT_VAL = 0;
#endif

	return;
}



