ENDIAN_MODE = big
FAX_LB_TEST = 0
#TCSUPPORT_SLIC_SEPARATE = 1

CONFIG += -D OSBN_VOIP -D SERENA_FXO_MODIFY -DSERENA_DO_CFG -DSERENA_DO_TEST -D BIG_ENDIAN -D SERENA_MODIFY -D PORK_MODIFY -D FAXLAB_DET -D T38_V29_WORKAROUND -D RTP_REDUNDANCY_2833 -D RTP_REDUNDANCY -D NEW_OPTIMIZE
#RTP_REDUNDANCY_2833 & RTP_REDUNDANCY are all controled by redundancy enable by strm config 
ifeq ($(TCSUPPORT_SLIC_SEPARATE),1)
CONFIG += -D TCSUPPORT_SLIC_SEPARATE
endif
ifeq ($(SLIC),SILICON)
CONFIG += -D SLIC_SILICON
endif

ifeq ($(ENDIAN_MODE),big)
CONFIG += -D BIG_ENDIAN
endif

ifeq ($(FAX_LB_TEST),1)
CONFIG += -D CONFIG_UL_T38_LB_MODE=1
endif

CONFIG += -D VOICE_QUALITY_IMPROVE

# -DFAX_LB_TEST -DCONFIG_PROFILE_FAX=1
ifneq ($(strip $(TCSUPPORT_VOIP_LED_APPCTRL)),)
export TCSUPPORT_VOIP_LED_APPCTRL
CONFIG += -D TCSUPPORT_VOIP_LED_APPCTRL
endif
