set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /opt/trendchip/mips-linux-uclibc-4.3.6-v2/usr/bin/mips-unknown-linux-uclibc-gcc)
set(CMAKE_CXX_COMPILER /opt/trendchip/mips-linux-uclibc-4.3.6-v2/usr/bin/mips-unknown-linux-uclibc-g++)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -pipe -Os  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CACHE STRING "Buildroot CFLAGS" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -pipe -Os  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64" CACHE STRING "Buildroot CXXFLAGS" FORCE)
set(CMAKE_INSTALL_SO_NO_EXE 0)
set(CMAKE_PROGRAM_PATH "/opt/trendchip/mips-linux-uclibc-4.3.6-v2/usr/bin")
set(CMAKE_FIND_ROOT_PATH "/opt/trendchip/mips-linux-uclibc-4.3.6-v2/usr/mips-unknown-linux-uclibc/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "/opt/trendchip/mips-linux-uclibc-4.3.6-v2/usr/mips-unknown-linux-uclibc/sysroot")
