/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux SSWLinux3 2.6.9-89.ELsmp #1 SMP Mon Apr 20 10:34:33 EDT 2009 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Mon Jul 11 16:26:00 CST 2011"
#define BUILD_ENV_SRCDIR "."
#define BUILD_ENV_BUILDDIR "."
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "SSWLinux3"
#define BUILD_ENV_COMPILER "mips-linux-gcc"
#endif /* _BUILD_ENV_H */
