#ifndef _WREPLD_PROTO_H_
#define _WREPLD_PROTO_H_

/* This file is automatically generated with "make proto". DO NOT EDIT */


/* The following definitions come from wrepld/parser.c  */

BOOL grow_buffer(struct BUFFER *buffer, int more);
void decode_generic_packet(struct BUFFER *inbuf, GENERIC_PACKET *q);
void encode_generic_packet(struct BUFFER *outbuf, GENERIC_PACKET *q);
void dump_generic_packet(GENERIC_PACKET *q);
void stop_packet(GENERIC_PACKET *q, GENERIC_PACKET *r, int reason);

/* The following definitions come from wrepld/partners.c  */

BOOL check_partner(int assoc);
BOOL add_partner(int client_assoc, int server_assoc, BOOL pull, BOOL push);
BOOL remove_partner(int client_assoc);
BOOL update_server_partner(int client_assoc, int server_assoc);
BOOL check_pull_partner(int assoc);
BOOL check_push_partner(int assoc);
int get_server_assoc(int assoc);
BOOL write_server_assoc_table(int client_assoc, struct in_addr partner, struct in_addr server);
BOOL get_server_assoc_table(int client_assoc, struct in_addr *partner, struct in_addr *server);

/* The following definitions come from wrepld/process.c  */

int init_wins_partner_table(void);
void construct_reply(struct wins_packet_struct *p);
void run_pull_replication(time_t t);
void run_push_replication(time_t t);

/* The following definitions come from wrepld/server.c  */

BOOL reload_services(BOOL test);
void exit_server(const char *reason);

/* The following definitions come from wrepld/socket.c  */

void add_fd_to_sock_array(int fd);
void remove_fd_from_sock_array(int fd);

#endif /*  _WREPLD_PROTO_H_  */
