/*
** Copyright (c) 2016 by Silicon Laboratories
**
** file: proslic_mlt_version.c
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/



char *ProSLICMLTAPIVersion= "3.0.0";



