/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ddns_Ddns */

#ifndef _Included_ddns_Ddns
#define _Included_ddns_Ddns
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif




/* Header for class dlna_Dlna */

#ifndef _Included_dlna_Dlna
#define _Included_dlna_Dlna
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif








/* Header for class ddns_DdnsService */

#ifndef _Included_ddns_DdnsService
#define _Included_ddns_DdnsService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ddns_DdnsService
 * Method:    DdnsAddJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ddns_DdnsService_DdnsAddJni
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     ddns_DdnsService
 * Method:    DdnsDelJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ddns_DdnsService_DdnsDelJni
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ddns_DdnsService
 * Method:    DdnsGetJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ddns_DdnsService_DdnsGetJni
  (JNIEnv *, jobject);

/*
 * Class:     ddns_DdnsService
 * Method:    startDdnsJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ddns_DdnsService_startDdnsJni
  (JNIEnv *, jobject);

/*
 * Class:     ddns_DdnsService
 * Method:    stopDdnsJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ddns_DdnsService_stopDdnsJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif



/* Header for class dlna_DlnaService */

#ifndef _Included_dlna_DlnaService
#define _Included_dlna_DlnaService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dlna_DlnaService
 * Method:    startDlnaJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dlna_DlnaService_startDlnaJni
  (JNIEnv *, jobject);

/*
 * Class:     dlna_DlnaService
 * Method:    stopDlnaJni
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dlna_DlnaService_stopDlnaJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif