
/* autogenerated - do not edit */
#include "jim.h"
#include "jimautoconf.h"
int Jim_InitStaticExtensions(Jim_Interp *interp)

{
	extern int Jim_aioInit(Jim_Interp *);
	extern int Jim_arrayInit(Jim_Interp *);
	extern int Jim_clockInit(Jim_Interp *);
	extern int Jim_eventloopInit(Jim_Interp *);
	extern int Jim_execInit(Jim_Interp *);
	extern int Jim_fileInit(Jim_Interp *);
	extern int Jim_packageInit(Jim_Interp *);
	extern int Jim_readdirInit(Jim_Interp *);
	extern int Jim_regexpInit(Jim_Interp *);
	extern int Jim_tclcompatInit(Jim_Interp *);
	extern int Jim_globInit(Jim_Interp *);
	Jim_aioInit(interp);
	Jim_arrayInit(interp);
	Jim_clockInit(interp);
	Jim_eventloopInit(interp);
	Jim_execInit(interp);
	Jim_fileInit(interp);
	Jim_packageInit(interp);
	Jim_readdirInit(interp);
	Jim_regexpInit(interp);
	Jim_tclcompatInit(interp);
	Jim_globInit(interp);
	return JIM_OK;
}
