#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','m','i','p','s','-','b','u','i',
        'l','d','r','o','o','t','-','l','i','n','u','x','-','g','n','u','-','g',
        'c','c',' ','-','m','i','p','s','3','2','r','2',' ','-','m','s','o','f',
        't','-','f','l','o','a','t',' ','-','I','.',' ','-','I','.','.',' ','-',
        'I','.','.','/','i','n','c','l','u','d','e',' ',' ','-','f','P','I','C',
        ' ','-','D','O','P','E','N','S','S','L','_','P','I','C',' ','-','D','O',
        'P','E','N','S','S','L','_','T','H','R','E','A','D','S',' ','-','D','_',
        'R','E','E','N','T','R','A','N','T',' ','-','D','D','S','O','_','D','L',
        'F','C','N',' ','-','D','H','A','V','E','_','D','L','F','C','N','_','H',
        ' ','-','D','L','_','E','N','D','I','A','N',' ','-','O','3',' ','-','f',
        'o','m','i','t','-','f','r','a','m','e','-','p','o','i','n','t','e','r',
        ' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-elf"
    #define DATE "built on: Tue Nov 29 16:19:39 2016"
#endif
