/*
 * Generated by gdbus-codegen 2.41.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "IgdTest-generated.h"

#include <string.h>
#if 0//def G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface com.ctc.igd1.Properties
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:IgdTestProperties
 * @title: IgdTestProperties
 * @short_description: Generated C code for the com.ctc.igd1.Properties D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.ctc.igd1.Properties ---- */

static const _ExtendedGDBusArgInfo _igd_test_properties_method_info_test_IN_ARG_input =
{
  {
    -1,
    (gchar *) "input",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _igd_test_properties_method_info_test_IN_ARG_pointers[] =
{
  &_igd_test_properties_method_info_test_IN_ARG_input,
  NULL
};

static const _ExtendedGDBusArgInfo _igd_test_properties_method_info_test_OUT_ARG_output =
{
  {
    -1,
    (gchar *) "output",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _igd_test_properties_method_info_test_OUT_ARG_pointers[] =
{
  &_igd_test_properties_method_info_test_OUT_ARG_output,
  NULL
};

static const _ExtendedGDBusMethodInfo _igd_test_properties_method_info_test =
{
  {
    -1,
    (gchar *) "Test",
    (GDBusArgInfo **) &_igd_test_properties_method_info_test_IN_ARG_pointers,
    (GDBusArgInfo **) &_igd_test_properties_method_info_test_OUT_ARG_pointers,
    NULL
  },
  "handle-test",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _igd_test_properties_method_info_pointers[] =
{
  &_igd_test_properties_method_info_test,
  NULL
};

static const _ExtendedGDBusPropertyInfo _igd_test_properties_property_info_result =
{
  {
    -1,
    (gchar *) "Result",
    (gchar *) "s",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "result",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _igd_test_properties_property_info_pointers[] =
{
  &_igd_test_properties_property_info_result,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _igd_test_properties_interface_info =
{
  {
    -1,
    (gchar *) "com.ctc.igd1.Properties",
    (GDBusMethodInfo **) &_igd_test_properties_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_igd_test_properties_property_info_pointers,
    NULL
  },
  "properties",
};


/**
 * igd_test_properties_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
igd_test_properties_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct;
}

/**
 * igd_test_properties_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #IgdTestProperties interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
igd_test_properties_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "result");
  return property_id_begin - 1;
}



/**
 * IgdTestProperties:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link>.
 */

/**
 * IgdTestPropertiesIface:
 * @parent_iface: The parent interface.
 * @handle_test: Handler for the #IgdTestProperties::handle-test signal.
 * @get_result: Getter for the #IgdTestProperties:result property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link>.
 */

typedef IgdTestPropertiesIface IgdTestPropertiesInterface;
G_DEFINE_INTERFACE (IgdTestProperties, igd_test_properties, G_TYPE_OBJECT);

static void
igd_test_properties_default_init (IgdTestPropertiesIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * IgdTestProperties::handle-test:
   * @object: A #IgdTestProperties.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_input: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-ctc-igd1-Properties.Test">Test()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call igd_test_properties_complete_test() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-test",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (IgdTestPropertiesIface, handle_test),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_UINT);

  /* GObject properties for D-Bus properties: */
  /**
   * IgdTestProperties:result:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-ctc-igd1-Properties.Result">"Result"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_string ("result", "Result", "Result", NULL, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * igd_test_properties_get_result: (skip)
 * @object: A #IgdTestProperties.
 *
 * Gets the value of the <link linkend="gdbus-property-com-ctc-igd1-Properties.Result">"Result"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * <warning>The returned value is only valid until the property changes so on the client-side it is only safe to use this function on the thread where @object was constructed. Use igd_test_properties_dup_result() if on another thread.</warning>
 *
 * Returns: (transfer none): The property value or %NULL if the property is not set. Do not free the returned value, it belongs to @object.
 */
const gchar *
igd_test_properties_get_result (IgdTestProperties *object)
{
  return IGD_TEST_PROPERTIES_GET_IFACE (object)->get_result (object);
}

/**
 * igd_test_properties_dup_result: (skip)
 * @object: A #IgdTestProperties.
 *
 * Gets a copy of the <link linkend="gdbus-property-com-ctc-igd1-Properties.Result">"Result"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: (transfer full): The property value or %NULL if the property is not set. The returned value should be freed with g_free().
 */
gchar *
igd_test_properties_dup_result (IgdTestProperties *object)
{
  gchar *value;
  g_object_get (G_OBJECT (object), "result", &value, NULL);
  return value;
}

/**
 * igd_test_properties_set_result: (skip)
 * @object: A #IgdTestProperties.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-ctc-igd1-Properties.Result">"Result"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
igd_test_properties_set_result (IgdTestProperties *object, const gchar *value)
{
  g_object_set (G_OBJECT (object), "result", value, NULL);
}

/**
 * igd_test_properties_call_test:
 * @proxy: A #IgdTestPropertiesProxy.
 * @arg_input: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-ctc-igd1-Properties.Test">Test()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_properties_call_test_finish() to get the result of the operation.
 *
 * See igd_test_properties_call_test_sync() for the synchronous, blocking version of this method.
 */
void
igd_test_properties_call_test (
    IgdTestProperties *proxy,
    guint arg_input,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Test",
    g_variant_new ("(u)",
                   arg_input),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * igd_test_properties_call_test_finish:
 * @proxy: A #IgdTestPropertiesProxy.
 * @out_output: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_properties_call_test().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with igd_test_properties_call_test().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
igd_test_properties_call_test_finish (
    IgdTestProperties *proxy,
    gchar **out_output,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_output);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * igd_test_properties_call_test_sync:
 * @proxy: A #IgdTestPropertiesProxy.
 * @arg_input: Argument to pass with the method invocation.
 * @out_output: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-ctc-igd1-Properties.Test">Test()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See igd_test_properties_call_test() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
igd_test_properties_call_test_sync (
    IgdTestProperties *proxy,
    guint arg_input,
    gchar **out_output,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Test",
    g_variant_new ("(u)",
                   arg_input),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_output);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * igd_test_properties_complete_test:
 * @object: A #IgdTestProperties.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @output: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-ctc-igd1-Properties.Test">Test()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
igd_test_properties_complete_test (
    IgdTestProperties *object,
    GDBusMethodInvocation *invocation,
    const gchar *output)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   output));
}

/* ------------------------------------------------------------------------ */

/**
 * IgdTestPropertiesProxy:
 *
 * The #IgdTestPropertiesProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * IgdTestPropertiesProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #IgdTestPropertiesProxy.
 */

struct _IgdTestPropertiesProxyPrivate
{
  GData *qdata;
};

static void igd_test_properties_proxy_iface_init (IgdTestPropertiesIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (IgdTestPropertiesProxy, igd_test_properties_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (IgdTestPropertiesProxy)
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_PROPERTIES, igd_test_properties_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (IgdTestPropertiesProxy, igd_test_properties_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_PROPERTIES, igd_test_properties_proxy_iface_init));

#endif
static void
igd_test_properties_proxy_finalize (GObject *object)
{
  IgdTestPropertiesProxy *proxy = IGD_TEST_PROPERTIES_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (igd_test_properties_proxy_parent_class)->finalize (object);
}

static void
igd_test_properties_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _igd_test_properties_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
igd_test_properties_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface com.ctc.igd1.Properties: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
igd_test_properties_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _igd_test_properties_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "com.ctc.igd1.Properties", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) igd_test_properties_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
igd_test_properties_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], IGD_TEST_TYPE_PROPERTIES);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, IGD_TEST_TYPE_PROPERTIES);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
igd_test_properties_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  IgdTestPropertiesProxy *proxy = IGD_TEST_PROPERTIES_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static const gchar *
igd_test_properties_proxy_get_result (IgdTestProperties *object)
{
  IgdTestPropertiesProxy *proxy = IGD_TEST_PROPERTIES_PROXY (object);
  GVariant *variant;
  const gchar *value = NULL;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Result");
  if (variant != NULL)
    {
      value = g_variant_get_string (variant, NULL);
      g_variant_unref (variant);
    }
  return value;
}

static void
igd_test_properties_proxy_init (IgdTestPropertiesProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = igd_test_properties_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, IGD_TEST_TYPE_PROPERTIES_PROXY, IgdTestPropertiesProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), igd_test_properties_interface_info ());
}

static void
igd_test_properties_proxy_class_init (IgdTestPropertiesProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = igd_test_properties_proxy_finalize;
  gobject_class->get_property = igd_test_properties_proxy_get_property;
  gobject_class->set_property = igd_test_properties_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = igd_test_properties_proxy_g_signal;
  proxy_class->g_properties_changed = igd_test_properties_proxy_g_properties_changed;

  igd_test_properties_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (IgdTestPropertiesProxyPrivate));
#endif
}

static void
igd_test_properties_proxy_iface_init (IgdTestPropertiesIface *iface)
{
  iface->get_result = igd_test_properties_proxy_get_result;
}

/**
 * igd_test_properties_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_properties_proxy_new_finish() to get the result of the operation.
 *
 * See igd_test_properties_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
igd_test_properties_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (IGD_TEST_TYPE_PROPERTIES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.Properties", NULL);
}

/**
 * igd_test_properties_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_properties_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with igd_test_properties_proxy_new().
 *
 * Returns: (transfer full) (type IgdTestPropertiesProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestProperties *
igd_test_properties_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return IGD_TEST_PROPERTIES (ret);
  else
    return NULL;
}

/**
 * igd_test_properties_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See igd_test_properties_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type IgdTestPropertiesProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestProperties *
igd_test_properties_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (IGD_TEST_TYPE_PROPERTIES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.Properties", NULL);
  if (ret != NULL)
    return IGD_TEST_PROPERTIES (ret);
  else
    return NULL;
}


/**
 * igd_test_properties_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like igd_test_properties_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_properties_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See igd_test_properties_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
igd_test_properties_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (IGD_TEST_TYPE_PROPERTIES_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.Properties", NULL);
}

/**
 * igd_test_properties_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_properties_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with igd_test_properties_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type IgdTestPropertiesProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestProperties *
igd_test_properties_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return IGD_TEST_PROPERTIES (ret);
  else
    return NULL;
}

/**
 * igd_test_properties_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like igd_test_properties_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See igd_test_properties_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type IgdTestPropertiesProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestProperties *
igd_test_properties_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (IGD_TEST_TYPE_PROPERTIES_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.Properties", NULL);
  if (ret != NULL)
    return IGD_TEST_PROPERTIES (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * IgdTestPropertiesSkeleton:
 *
 * The #IgdTestPropertiesSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * IgdTestPropertiesSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #IgdTestPropertiesSkeleton.
 */

struct _IgdTestPropertiesSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_igd_test_properties_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], IGD_TEST_TYPE_PROPERTIES);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#if 0//def G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, IGD_TEST_TYPE_PROPERTIES);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_igd_test_properties_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_igd_test_properties_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_properties_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _igd_test_properties_skeleton_vtable =
{
  _igd_test_properties_skeleton_handle_method_call,
  _igd_test_properties_skeleton_handle_get_property,
  _igd_test_properties_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
igd_test_properties_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return igd_test_properties_interface_info ();
}

static GDBusInterfaceVTable *
igd_test_properties_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_igd_test_properties_skeleton_vtable;
}

static GVariant *
igd_test_properties_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_igd_test_properties_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _igd_test_properties_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _igd_test_properties_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _igd_test_properties_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.ctc.igd1.Properties", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _igd_test_properties_emit_changed (gpointer user_data);

static void
igd_test_properties_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _igd_test_properties_emit_changed (skeleton);
}

static void igd_test_properties_skeleton_iface_init (IgdTestPropertiesIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (IgdTestPropertiesSkeleton, igd_test_properties_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (IgdTestPropertiesSkeleton)
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_PROPERTIES, igd_test_properties_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (IgdTestPropertiesSkeleton, igd_test_properties_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_PROPERTIES, igd_test_properties_skeleton_iface_init));

#endif
static void
igd_test_properties_skeleton_finalize (GObject *object)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (igd_test_properties_skeleton_parent_class)->finalize (object);
}

static void
igd_test_properties_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_igd_test_properties_emit_changed (gpointer user_data)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "com.ctc.igd1.Properties",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_igd_test_properties_schedule_emit_changed (IgdTestPropertiesSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
igd_test_properties_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _igd_test_properties_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _igd_test_properties_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
igd_test_properties_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _igd_test_properties_schedule_emit_changed (skeleton, _igd_test_properties_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
igd_test_properties_skeleton_init (IgdTestPropertiesSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = igd_test_properties_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, IGD_TEST_TYPE_PROPERTIES_SKELETON, IgdTestPropertiesSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_STRING);
}

static const gchar *
igd_test_properties_skeleton_get_result (IgdTestProperties *object)
{
  IgdTestPropertiesSkeleton *skeleton = IGD_TEST_PROPERTIES_SKELETON (object);
  const gchar *value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_string (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
igd_test_properties_skeleton_class_init (IgdTestPropertiesSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = igd_test_properties_skeleton_finalize;
  gobject_class->get_property = igd_test_properties_skeleton_get_property;
  gobject_class->set_property = igd_test_properties_skeleton_set_property;
  gobject_class->notify       = igd_test_properties_skeleton_notify;


  igd_test_properties_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = igd_test_properties_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = igd_test_properties_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = igd_test_properties_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = igd_test_properties_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (IgdTestPropertiesSkeletonPrivate));
#endif
}

static void
igd_test_properties_skeleton_iface_init (IgdTestPropertiesIface *iface)
{
  iface->get_result = igd_test_properties_skeleton_get_result;
}

/**
 * igd_test_properties_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-Properties.top_of_page">com.ctc.igd1.Properties</link>.
 *
 * Returns: (transfer full) (type IgdTestPropertiesSkeleton): The skeleton object.
 */
IgdTestProperties *
igd_test_properties_skeleton_new (void)
{
  return IGD_TEST_PROPERTIES (g_object_new (IGD_TEST_TYPE_PROPERTIES_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface com.ctc.igd1.ObjectManager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:IgdTestObjectManager
 * @title: IgdTestObjectManager
 * @short_description: Generated C code for the com.ctc.igd1.ObjectManager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link> D-Bus interface in C.
 */

/* ---- Introspection data for com.ctc.igd1.ObjectManager ---- */

static const _ExtendedGDBusArgInfo _igd_test_object_manager_method_info_add_OUT_ARG_inst =
{
  {
    -1,
    (gchar *) "inst",
    (gchar *) "u",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _igd_test_object_manager_method_info_add_OUT_ARG_pointers[] =
{
  &_igd_test_object_manager_method_info_add_OUT_ARG_inst,
  NULL
};

static const _ExtendedGDBusMethodInfo _igd_test_object_manager_method_info_add =
{
  {
    -1,
    (gchar *) "Add",
    NULL,
    (GDBusArgInfo **) &_igd_test_object_manager_method_info_add_OUT_ARG_pointers,
    NULL
  },
  "handle-add",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _igd_test_object_manager_method_info_pointers[] =
{
  &_igd_test_object_manager_method_info_add,
  NULL
};

static const _ExtendedGDBusPropertyInfo _igd_test_object_manager_property_info_instnum =
{
  {
    -1,
    (gchar *) "instnum",
    (gchar *) "u",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "instnum",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _igd_test_object_manager_property_info_pointers[] =
{
  &_igd_test_object_manager_property_info_instnum,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _igd_test_object_manager_interface_info =
{
  {
    -1,
    (gchar *) "com.ctc.igd1.ObjectManager",
    (GDBusMethodInfo **) &_igd_test_object_manager_method_info_pointers,
    NULL,
    (GDBusPropertyInfo **) &_igd_test_object_manager_property_info_pointers,
    NULL
  },
  "object-manager",
};


/**
 * igd_test_object_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
igd_test_object_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct;
}

/**
 * igd_test_object_manager_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #IgdTestObjectManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
igd_test_object_manager_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "instnum");
  return property_id_begin - 1;
}



/**
 * IgdTestObjectManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link>.
 */

/**
 * IgdTestObjectManagerIface:
 * @parent_iface: The parent interface.
 * @handle_add: Handler for the #IgdTestObjectManager::handle-add signal.
 * @get_instnum: Getter for the #IgdTestObjectManager:instnum property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link>.
 */

typedef IgdTestObjectManagerIface IgdTestObjectManagerInterface;
G_DEFINE_INTERFACE (IgdTestObjectManager, igd_test_object_manager, G_TYPE_OBJECT);

static void
igd_test_object_manager_default_init (IgdTestObjectManagerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * IgdTestObjectManager::handle-add:
   * @object: A #IgdTestObjectManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-com-ctc-igd1-ObjectManager.Add">Add()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call igd_test_object_manager_complete_add() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-add",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (IgdTestObjectManagerIface, handle_add),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject properties for D-Bus properties: */
  /**
   * IgdTestObjectManager:instnum:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-com-ctc-igd1-ObjectManager.instnum">"instnum"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_uint ("instnum", "instnum", "instnum", 0, G_MAXUINT32, 0, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * igd_test_object_manager_get_instnum: (skip)
 * @object: A #IgdTestObjectManager.
 *
 * Gets the value of the <link linkend="gdbus-property-com-ctc-igd1-ObjectManager.instnum">"instnum"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
guint 
igd_test_object_manager_get_instnum (IgdTestObjectManager *object)
{
  return IGD_TEST_OBJECT_MANAGER_GET_IFACE (object)->get_instnum (object);
}

/**
 * igd_test_object_manager_set_instnum: (skip)
 * @object: A #IgdTestObjectManager.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-com-ctc-igd1-ObjectManager.instnum">"instnum"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
igd_test_object_manager_set_instnum (IgdTestObjectManager *object, guint value)
{
  g_object_set (G_OBJECT (object), "instnum", value, NULL);
}

/**
 * igd_test_object_manager_call_add:
 * @proxy: A #IgdTestObjectManagerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-com-ctc-igd1-ObjectManager.Add">Add()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_object_manager_call_add_finish() to get the result of the operation.
 *
 * See igd_test_object_manager_call_add_sync() for the synchronous, blocking version of this method.
 */
void
igd_test_object_manager_call_add (
    IgdTestObjectManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Add",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * igd_test_object_manager_call_add_finish:
 * @proxy: A #IgdTestObjectManagerProxy.
 * @out_inst: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_object_manager_call_add().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with igd_test_object_manager_call_add().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
igd_test_object_manager_call_add_finish (
    IgdTestObjectManager *proxy,
    guint *out_inst,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_inst);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * igd_test_object_manager_call_add_sync:
 * @proxy: A #IgdTestObjectManagerProxy.
 * @out_inst: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-com-ctc-igd1-ObjectManager.Add">Add()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See igd_test_object_manager_call_add() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
igd_test_object_manager_call_add_sync (
    IgdTestObjectManager *proxy,
    guint *out_inst,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Add",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(u)",
                 out_inst);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * igd_test_object_manager_complete_add:
 * @object: A #IgdTestObjectManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @inst: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-com-ctc-igd1-ObjectManager.Add">Add()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
igd_test_object_manager_complete_add (
    IgdTestObjectManager *object,
    GDBusMethodInvocation *invocation,
    guint inst)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(u)",
                   inst));
}

/* ------------------------------------------------------------------------ */

/**
 * IgdTestObjectManagerProxy:
 *
 * The #IgdTestObjectManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * IgdTestObjectManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #IgdTestObjectManagerProxy.
 */

struct _IgdTestObjectManagerProxyPrivate
{
  GData *qdata;
};

static void igd_test_object_manager_proxy_iface_init (IgdTestObjectManagerIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (IgdTestObjectManagerProxy, igd_test_object_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (IgdTestObjectManagerProxy)
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_OBJECT_MANAGER, igd_test_object_manager_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (IgdTestObjectManagerProxy, igd_test_object_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_OBJECT_MANAGER, igd_test_object_manager_proxy_iface_init));

#endif
static void
igd_test_object_manager_proxy_finalize (GObject *object)
{
  IgdTestObjectManagerProxy *proxy = IGD_TEST_OBJECT_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (igd_test_object_manager_proxy_parent_class)->finalize (object);
}

static void
igd_test_object_manager_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _igd_test_object_manager_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
igd_test_object_manager_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface com.ctc.igd1.ObjectManager: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
igd_test_object_manager_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _igd_test_object_manager_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "com.ctc.igd1.ObjectManager", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) igd_test_object_manager_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
igd_test_object_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], IGD_TEST_TYPE_OBJECT_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, IGD_TEST_TYPE_OBJECT_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
igd_test_object_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  IgdTestObjectManagerProxy *proxy = IGD_TEST_OBJECT_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static guint 
igd_test_object_manager_proxy_get_instnum (IgdTestObjectManager *object)
{
  IgdTestObjectManagerProxy *proxy = IGD_TEST_OBJECT_MANAGER_PROXY (object);
  GVariant *variant;
  guint value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "instnum");
  if (variant != NULL)
    {
      value = g_variant_get_uint32 (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
igd_test_object_manager_proxy_init (IgdTestObjectManagerProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = igd_test_object_manager_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, IGD_TEST_TYPE_OBJECT_MANAGER_PROXY, IgdTestObjectManagerProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), igd_test_object_manager_interface_info ());
}

static void
igd_test_object_manager_proxy_class_init (IgdTestObjectManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = igd_test_object_manager_proxy_finalize;
  gobject_class->get_property = igd_test_object_manager_proxy_get_property;
  gobject_class->set_property = igd_test_object_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = igd_test_object_manager_proxy_g_signal;
  proxy_class->g_properties_changed = igd_test_object_manager_proxy_g_properties_changed;

  igd_test_object_manager_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (IgdTestObjectManagerProxyPrivate));
#endif
}

static void
igd_test_object_manager_proxy_iface_init (IgdTestObjectManagerIface *iface)
{
  iface->get_instnum = igd_test_object_manager_proxy_get_instnum;
}

/**
 * igd_test_object_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_object_manager_proxy_new_finish() to get the result of the operation.
 *
 * See igd_test_object_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
igd_test_object_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (IGD_TEST_TYPE_OBJECT_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.ObjectManager", NULL);
}

/**
 * igd_test_object_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_object_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with igd_test_object_manager_proxy_new().
 *
 * Returns: (transfer full) (type IgdTestObjectManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestObjectManager *
igd_test_object_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return IGD_TEST_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * igd_test_object_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See igd_test_object_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type IgdTestObjectManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestObjectManager *
igd_test_object_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (IGD_TEST_TYPE_OBJECT_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.ObjectManager", NULL);
  if (ret != NULL)
    return IGD_TEST_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * igd_test_object_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like igd_test_object_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call igd_test_object_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See igd_test_object_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
igd_test_object_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (IGD_TEST_TYPE_OBJECT_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.ObjectManager", NULL);
}

/**
 * igd_test_object_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to igd_test_object_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with igd_test_object_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type IgdTestObjectManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestObjectManager *
igd_test_object_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return IGD_TEST_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * igd_test_object_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like igd_test_object_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See igd_test_object_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type IgdTestObjectManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
IgdTestObjectManager *
igd_test_object_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (IGD_TEST_TYPE_OBJECT_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "com.ctc.igd1.ObjectManager", NULL);
  if (ret != NULL)
    return IGD_TEST_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * IgdTestObjectManagerSkeleton:
 *
 * The #IgdTestObjectManagerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * IgdTestObjectManagerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #IgdTestObjectManagerSkeleton.
 */

struct _IgdTestObjectManagerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_igd_test_object_manager_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], IGD_TEST_TYPE_OBJECT_MANAGER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#if 0 //def G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, IGD_TEST_TYPE_OBJECT_MANAGER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_igd_test_object_manager_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_igd_test_object_manager_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_igd_test_object_manager_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _igd_test_object_manager_skeleton_vtable =
{
  _igd_test_object_manager_skeleton_handle_method_call,
  _igd_test_object_manager_skeleton_handle_get_property,
  _igd_test_object_manager_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
igd_test_object_manager_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return igd_test_object_manager_interface_info ();
}

static GDBusInterfaceVTable *
igd_test_object_manager_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_igd_test_object_manager_skeleton_vtable;
}

static GVariant *
igd_test_object_manager_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_igd_test_object_manager_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _igd_test_object_manager_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _igd_test_object_manager_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _igd_test_object_manager_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "com.ctc.igd1.ObjectManager", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _igd_test_object_manager_emit_changed (gpointer user_data);

static void
igd_test_object_manager_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _igd_test_object_manager_emit_changed (skeleton);
}

static void igd_test_object_manager_skeleton_iface_init (IgdTestObjectManagerIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (IgdTestObjectManagerSkeleton, igd_test_object_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (IgdTestObjectManagerSkeleton)
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_OBJECT_MANAGER, igd_test_object_manager_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (IgdTestObjectManagerSkeleton, igd_test_object_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (IGD_TEST_TYPE_OBJECT_MANAGER, igd_test_object_manager_skeleton_iface_init));

#endif
static void
igd_test_object_manager_skeleton_finalize (GObject *object)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (igd_test_object_manager_skeleton_parent_class)->finalize (object);
}

static void
igd_test_object_manager_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_igd_test_object_manager_emit_changed (gpointer user_data)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "com.ctc.igd1.ObjectManager",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_igd_test_object_manager_schedule_emit_changed (IgdTestObjectManagerSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
igd_test_object_manager_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _igd_test_object_manager_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _igd_test_object_manager_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
igd_test_object_manager_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _igd_test_object_manager_schedule_emit_changed (skeleton, _igd_test_object_manager_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
igd_test_object_manager_skeleton_init (IgdTestObjectManagerSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = igd_test_object_manager_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, IGD_TEST_TYPE_OBJECT_MANAGER_SKELETON, IgdTestObjectManagerSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_UINT);
}

static guint 
igd_test_object_manager_skeleton_get_instnum (IgdTestObjectManager *object)
{
  IgdTestObjectManagerSkeleton *skeleton = IGD_TEST_OBJECT_MANAGER_SKELETON (object);
  guint value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_uint (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
igd_test_object_manager_skeleton_class_init (IgdTestObjectManagerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = igd_test_object_manager_skeleton_finalize;
  gobject_class->get_property = igd_test_object_manager_skeleton_get_property;
  gobject_class->set_property = igd_test_object_manager_skeleton_set_property;
  gobject_class->notify       = igd_test_object_manager_skeleton_notify;


  igd_test_object_manager_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = igd_test_object_manager_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = igd_test_object_manager_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = igd_test_object_manager_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = igd_test_object_manager_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (IgdTestObjectManagerSkeletonPrivate));
#endif
}

static void
igd_test_object_manager_skeleton_iface_init (IgdTestObjectManagerIface *iface)
{
  iface->get_instnum = igd_test_object_manager_skeleton_get_instnum;
}

/**
 * igd_test_object_manager_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-com-ctc-igd1-ObjectManager.top_of_page">com.ctc.igd1.ObjectManager</link>.
 *
 * Returns: (transfer full) (type IgdTestObjectManagerSkeleton): The skeleton object.
 */
IgdTestObjectManager *
igd_test_object_manager_skeleton_new (void)
{
  return IGD_TEST_OBJECT_MANAGER (g_object_new (IGD_TEST_TYPE_OBJECT_MANAGER_SKELETON, NULL));
}

int init_test(GDBusConnection *connection)
{
	GError *error = NULL;
	IgdTestObjectManager *object = igd_test_object_manager_skeleton_new();
	g_printf("%s entered!\r\n", __FUNCTION__);

	
	guint id = g_dbus_interface_skeleton_export (G_DBUS_INTERFACE_SKELETON(object),
											 connection,
											 "/com/ctc/igd1/test",
											 &error);

	IgdTestProperties *object1 = igd_test_properties_skeleton_new();
	g_printf("%s entered!\r\n", __FUNCTION__);
	
	id = g_dbus_interface_skeleton_export (G_DBUS_INTERFACE_SKELETON(object1),
											 connection,
											 "/com/ctc/igd1/test",
											 &error);

	g_assert_no_error (error);
}


