/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux szxbb102 2.6.9-89.ELsmp #1 SMP Mon Apr 20 10:34:33 EDT 2009 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Tue Nov  8 17:16:53 CST 2011"
#define BUILD_ENV_SRCDIR "/mnt/user/socsw/jiehao_sz/Samba_over_IPv6/tclinux_phoenix/apps/public/samba-3.2.5/source"
#define BUILD_ENV_BUILDDIR "/mnt/user/socsw/jiehao_sz/Samba_over_IPv6/tclinux_phoenix/apps/public/samba-3.2.5/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "szxbb102"
#define BUILD_ENV_COMPILER "mips-linux-gcc"
#endif /* _BUILD_ENV_H */
