/*
 * ZLR96622_SM2_FULL.c --
 *
 * This file contains profile data in byte format
 *
 * Project Info --
 *   File:   C:\Microsemi\VoicePath API-II Lite P2.23.0_VVP886_P1.3.0\coefficient_sets\miSLIC\ZLR96622_BB_ABS\ZLR96622_SM2_LITE.vpw
 *   Type:   Design for ZLR96822 SM2 Line Module Featuring the Le9662, Lite Coefficients
 *   Date:   Monday, September 08, 2014 00:01:22
 *   Device: miSLIC Le9662_A
 *
 *   This file was generated with Profile Wizard Version: P2.6.0
 *
 * Project Comments --
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  Profile Wizard Coefficient Revision 2.9 Release Notes:
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  I. General:
 *  1. This release includes support for the following 44 countries:
 *  Argentina (AR), Austria (AT), Australia (AU), Belgium (BE), Brazil (BR), Bulgaria (BG), Canada (CA), Switzerland (CH),
 *  Chile (CL), China (CN), Czech Republic (CZ), Germany (DE), Denmark (DK), Ecuador (EC), Spain (ES), Finland (FI),
 *  France (FR), UK (GB), Greece (GR), Hong Kong SAR China (HK), Hungary (HU), Indonesia (ID), Ireland (IE), Israel (IL),
 *  India (IN), Iceland (IS), Italy (IT), Japan (JP), S. Korea (KR), Mexico (MX), Malaysia (MY), Netherlands (NL),
 *  Norway (NO), New Zealand (NZ), Poland (PL), Portugal (PT), Russian Federation (RU), Sweden (SE), Singapore (SG),
 *  Thailand (TH), Turkey (TK), Taiwan (TW), USA (US), and South Africa (ZA).
 *  2. The coefficients in this and all releases are provided for use only with the Microsemi VoicePath API-II (VP-API-II). Please refer 
 *  to the terms and conditions for licensing the software regarding terms and conditions of usage. These profiles are provided for 
 *  reference only with no guarantee whatsoever by Microsemi Corporation.
 *  3. This release is for the ZLR96822 SM2 Line Module based on the Le9662.
 *  
 *  II. Device Profiles:
 *  1. Two device profiles are included.  ZLR88822_ABS_47UH_DEVICE is intended for power supply designs using a 47uH inductor.
 *  ZLR88822_ABS_100UH_DEVICE is intended for use with a 100uH inductor.
 *  
 *  III. DC Profiles:
 *  1. The DC_FXS_VE960_ABS100V_DEF Profile is the default unless a country specific profile is selected. Example DC profile settings are
 *  provided for China, ETSI and the USA.
 *  
 *  IV. AC Profiles:
 *  1. FXS Coefficients assume -6dBr RX (Output from chipset) and 0dB TX relative gain levels.
 *  2. Supported countries not individually listed should use the default 600R profile AC_FXS_RF14_600R_DEF.
 *  4. AC FXS Coefficients assume the use of two 7 ohm series resistors or PTCs. Customers using other PTC resistance values (such as 
 *  25ohms or 50 ohms) should not use these AC coefficients and can request alternate ones from Microsemi.
 *  5. This release includes both Narrowband and Wideband coefficients. Note that the VE960 Series devices support per channel Narrowband or
 *  Wideband audio selection.
 *  
 *  V. Ring Profiles:
 *  1. RING_VE960_ABS100V_DEF is the default ringing profile and should be used for all countries which do not have a listed ringing profile.  
 *  The default ringing profile is set for a sine wave ringing with an amplitude of 50Vrms (70.7Vpk)with no DC bias and a frequency of 25 Hz 
 *  generated by fixed (non-tracking) supply.
 *  2. Most ringing profiles on the list are sinusoidal with an amplitude of 50Vrms with no DC bias generated by fixed (non-tracking) supply. 
 *  3. The ringing definitions may be changed based on the requirements of the target market as long as the total amplitude (AC + DC 
 *  components) does not exceed the limits set forth in the Le9662 data sheet.
 *  
 *  VI. Tone Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VII. Cadence Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VIII. Caller ID Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  IX. Metering Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  (c) Copyright 2013 Microsemi Corporation. All rights reserved.
 *  
 *  -----------------------------------------------------------------------------------------------------------------------------------------------------
 */

#include "ZLR96622_SM2_FULL.h"


/************** Device Profile **************/

/* Device Configuration Data - 47uH Inductor */
const VpProfileDataType LE9662_DEV_PROFILE_47UH[] =
{
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0xFF, 0x00,       /* Device Profile for Le9662_A device */
   0x2C,                   /* Profile length = 44 + 4 = 48 bytes */
   0x05,                   /* Profile format version = 5 */
   0x14,                   /* MPI section length = 20 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0x46, 0x82,             /* PCLK = 2.048 MHz; INTM = Open Drain */
   0x44, 0x46,             /* PCM Clock Slot = 6 TX / 0 RX; XE = Pos. */
   0x5E, 0x14, 0x00,       /* Device Mode Register */
   0xF6, 0x95, 0x00, 0x94, /* Switching Regulator Timing Params */
         0x30, 0x94, 0x30,
   0xE4, 0x04, 0xA0, 0x00, /* Switching Regulator Params */
   0xE6, 0x60,             /* Switching Regulator Control */
/* Formatted Parameters Section -------------------------------------------- */
   0x22,                   /* IO21 Mode: Analog Voltage Sense */
                           /* IO22 Mode: Analog Voltage Sense */
   0x20,                   /* Dial pulse correction: 2 ms */
                           /* Switcher Configuration = BuckBoost ABS 47uH (12 V in) */
   0x00, 0xFF,             /* Over-current shutdown count = 255 */
   0x21,                   /* Leading edge blanking window = 81 ns */
                           /* ABS supply config: 1 = Single; 2 = Slave */
   0x30, 0x14, 0x30, 0x14, /* Free-Run Timing Parameters */
         0x30, 0x14,
   0x19,                   /* Switcher 1 Voltage = 25 V */
   0x3C,                   /* Switcher 2 Voltage = 60 V */
   0xFF,
   0x95, 0x00,             /* Low-Power Timing Parameters */
   0x2D, 0x6E,             /* Switcher Limit Voltages 45 V, 110 V */
   0x02,                   /* Charge pump disabled */
                           /* Charge Pump Overload Protection: Switcher Cycle Skip */
   0x3C,                   /* Switcher Input 12 V */
   0x02, 0xFD              /* VBH Offset 2 V, VBH Overhead -3 V */
};

/************** DC Profile **************/

/* DC FXS Defaults - Use for all countries unless country file exists - 23mA Current Feed */
const VpProfileDataType DC_FXS_VE960_ABS100V_DEF[] =
{
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x01, 0x00,       /* DC Profile for Le9662_A device */
   0x0B,                   /* Profile length = 11 + 4 = 15 bytes */
   0x02,                   /* Profile format version = 2 */
   0x03,                   /* MPI section length = 3 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xC6, 0x91, 0xE5,       /* DC Feed Parameters: ir_overhead = 100 ohm; */
                           /* VOC = 48 V; LI = 50 ohm; ILA = 23 mA */
                           /* Battery Switch Offset Voltage = 4.02 V */
/* Formatted Parameters Section -------------------------------------------- */
   0x1C,                   /* Switch Hook Threshold = 11 mA */
                           /* Ground-Key Threshold = 18 mA */
   0x86,                   /* Switch Hook Debounce = 12 ms */
                           /* Ground-Key Debounce = 16 ms */
   0x58,                   /* Low-Power Switch Hook Hysteresis = 2 V */
                           /* Ground-Key Hysteresis = 6 mA */
                           /* Switch Hook Hysteresis = 2 mA */
   0x80,                   /* Low-Power Switch Hook Threshold = 22 V */
   0x00,                   /* R_OSP = 0 ohms */
   0x07                    /* R_ISP = 7 ohms */
};

/************** AC Profile **************/

/* AC FXS RF14 600R Normal Coefficients (Default)  */
const VpProfileDataType AC_FXS_VE960_RF14_600R_DEF[] =
{
  /* AC Profile */
 0xA4, 0x00, 0xF4, 0x4C, 0x01, 0x49, 0xCA, 0xF5, 0x98, 0xAA, 0x7B, 0xAB,
 0x2C, 0xA3, 0x25, 0xA5, 0x24, 0xB2, 0x3D, 0x9A, 0x2A, 0xAA, 0xA6, 0x9F,
 0x01, 0x8A, 0x1D, 0x01, 0xA3, 0xA0, 0x2E, 0xB2, 0xB2, 0xBA, 0xAC, 0xA2,
 0xA6, 0xCB, 0x3B, 0x45, 0x88, 0x2A, 0x20, 0x3C, 0xBC, 0x4E, 0xA6, 0x2B,
 0xA5, 0x2B, 0x3E, 0xBA, 0x8F, 0x82, 0xA8, 0x71, 0x80, 0xA9, 0xF0, 0x50,
 0x00, 0x86, 0x2A, 0x42, 0xA1, 0xCB, 0x1B, 0xA3, 0xA8, 0xFB, 0x87, 0xAA,
 0xFB, 0x9F, 0xA9, 0xF0, 0x96, 0x2E, 0x01, 0x00
};

/************** Ringing Profile **************/

/* Default Ringing 25Hz 50Vrms Fixed, AC Trip - Use for all countries unless country profile exists */
const VpProfileDataType RING_VE960_ABS100V_DEF[] =
{
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x04, 0x00,       /* Ringing Profile for Le9662_A device */
   0x12,                   /* Profile length = 18 + 4 = 22 bytes */
   0x01,                   /* Profile format version = 1 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xC0, 0x08, 0x00, 0x00, /* Ringing Generator Parameters: */
         0x00, 0x44, 0x3A, /* 24.9 Hz Sine; 1.41 CF; 70.70 Vpk; 0.00 V bias */
         0x9D, 0x00, 0x00, /* Ring trip cycles = 1; RTHALFCYC = 0 */
         0x00, 0x00,
/* Formatted Parameters Section -------------------------------------------- */
   0xAA,                   /* Ring Trip Method = AC; Threshold = 21.0 mA */
   0x02,                   /* Ringing Current Limit = 54 mA */
   0x4E,                   /* Fixed; Max Ringing Supply = 75 V */
   0x00                    /* Balanced; Ring Cadence Control Disabled */
};

/* Default Ringing 25Hz 60Vrms Fixed, AC Trip */
const VpProfileDataType RING_MISLIC_ABS100V_CHINA_TRAPE_9642[] =
{
/* Profile Header ---------------------------------------------------------- */
   0x0C, 0x04, 0x00,       /* Ringing Profile for Le9642 device */
   0x12,                   /* Profile length = 18 + 4 = 22 bytes */
   0x01,                   /* Profile format version = 1 */
   0x0C,                   /* MPI section length = 12 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xC0, 0x09, 0x00, 0x00, /* Ringing Generator Parameters: */
         0x00, 0xB5, 0x46, /* 24.9 Hz Trap; 1.42 CF; 85.00 Vpk; 0.00 V bias */
         0x77, 0x01, 0x41, /* Ring trip cycles = 1; RTHALFCYC = 0 */
         0x00, 0x00,
/* Formatted Parameters Section -------------------------------------------- */
   0xBC,                   /* Ring Trip Method = AC; Threshold = 30.0 mA */
   0x05,                   /* Ringing Current Limit = 60 mA */
   0x50,                   /* Fixed; Max Ringing Supply = 85 V */
   0x00                    /* Balanced; Ring Cadence Control Disabled */
};

/************** Tone Profile **************/

/************** Cadence Profile **************/

/************** Caller ID Profile **************/

/************** Metering_Profile **************/
/* Metering Index 1 */  //dyma_20140428
const VpProfileDataType METER_LE9662_12KHZ[] =
{
/* Profile Header ---------------------------------------------------------- */
   0x0D, 0x07, 0x00,       /* Metering Profile for ZL88601 device */
   0x08,                   /* Profile length = 8 + 4 = 12 bytes */
   0x00,                   /* Profile format version = 0 */
   0x05,                   /* MPI section length = 5 bytes */
/* Raw MPI Section --------------------------------------------------------- */
   0xD0, 0x20,             /* MTRF = 12 kHz; MLIM = 496.0/701.4 mV RMS/peak */
         0x25,             /* SOREV = Smooth; MTRSL = 2.516/3.558 mA RMS/peak */
         0x00, 0x00,
/* Formatted Parameters Section -------------------------------------------- */
   0x00                    /* Reserved */
};

/* end of file ZLR96622_SM2_FULL.c */
