/*
 * ZLR96622_SM2_FULL.h --
 *
 * This header file exports the Profile data types
 *
 * Project Info --
 *   File:   C:\Microsemi\VoicePath API-II Lite P2.23.0_VVP886_P1.3.0\coefficient_sets\miSLIC\ZLR96622_BB_ABS\ZLR96622_SM2_LITE.vpw
 *   Type:   Design for ZLR96822 SM2 Line Module Featuring the Le9662, Lite Coefficients
 *   Date:   Monday, September 08, 2014 00:01:22
 *   Device: miSLIC Le9662_A
 *
 *   This file was generated with Profile Wizard Version: P2.6.0
 *
 * Project Comments --
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  Profile Wizard Coefficient Revision 2.9 Release Notes:
 *  ----------------------------------------------------------------------------------------------------------------------------------
 *  I. General:
 *  1. This release includes support for the following 44 countries:
 *  Argentina (AR), Austria (AT), Australia (AU), Belgium (BE), Brazil (BR), Bulgaria (BG), Canada (CA), Switzerland (CH),
 *  Chile (CL), China (CN), Czech Republic (CZ), Germany (DE), Denmark (DK), Ecuador (EC), Spain (ES), Finland (FI),
 *  France (FR), UK (GB), Greece (GR), Hong Kong SAR China (HK), Hungary (HU), Indonesia (ID), Ireland (IE), Israel (IL),
 *  India (IN), Iceland (IS), Italy (IT), Japan (JP), S. Korea (KR), Mexico (MX), Malaysia (MY), Netherlands (NL),
 *  Norway (NO), New Zealand (NZ), Poland (PL), Portugal (PT), Russian Federation (RU), Sweden (SE), Singapore (SG),
 *  Thailand (TH), Turkey (TK), Taiwan (TW), USA (US), and South Africa (ZA).
 *  2. The coefficients in this and all releases are provided for use only with the Microsemi VoicePath API-II (VP-API-II). Please refer 
 *  to the terms and conditions for licensing the software regarding terms and conditions of usage. These profiles are provided for 
 *  reference only with no guarantee whatsoever by Microsemi Corporation.
 *  3. This release is for the ZLR96822 SM2 Line Module based on the Le9662.
 *  
 *  II. Device Profiles:
 *  1. Two device profiles are included.  ZLR88822_ABS_47UH_DEVICE is intended for power supply designs using a 47uH inductor.
 *  ZLR88822_ABS_100UH_DEVICE is intended for use with a 100uH inductor.
 *  
 *  III. DC Profiles:
 *  1. The DC_FXS_VE960_ABS100V_DEF Profile is the default unless a country specific profile is selected. Example DC profile settings are
 *  provided for China, ETSI and the USA.
 *  
 *  IV. AC Profiles:
 *  1. FXS Coefficients assume -6dBr RX (Output from chipset) and 0dB TX relative gain levels.
 *  2. Supported countries not individually listed should use the default 600R profile AC_FXS_RF14_600R_DEF.
 *  4. AC FXS Coefficients assume the use of two 7 ohm series resistors or PTCs. Customers using other PTC resistance values (such as 
 *  25ohms or 50 ohms) should not use these AC coefficients and can request alternate ones from Microsemi.
 *  5. This release includes both Narrowband and Wideband coefficients. Note that the VE960 Series devices support per channel Narrowband or
 *  Wideband audio selection.
 *  
 *  V. Ring Profiles:
 *  1. RING_VE960_ABS100V_DEF is the default ringing profile and should be used for all countries which do not have a listed ringing profile.  
 *  The default ringing profile is set for a sine wave ringing with an amplitude of 50Vrms (70.7Vpk)with no DC bias and a frequency of 25 Hz 
 *  generated by fixed (non-tracking) supply.
 *  2. Most ringing profiles on the list are sinusoidal with an amplitude of 50Vrms with no DC bias generated by fixed (non-tracking) supply. 
 *  3. The ringing definitions may be changed based on the requirements of the target market as long as the total amplitude (AC + DC 
 *  components) does not exceed the limits set forth in the Le9662 data sheet.
 *  
 *  VI. Tone Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VII. Cadence Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  VIII. Caller ID Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  IX. Metering Profiles:
 *  1. These profiles are available only in the full version of the VP-API-II.
 *  
 *  (c) Copyright 2013 Microsemi Corporation. All rights reserved.
 *  
 *  -----------------------------------------------------------------------------------------------------------------------------------------------------
 */

#ifndef ZLR96622_SM2_FULL_H
#define ZLR96622_SM2_FULL_H

#ifdef VP_API_TYPES_H
#include "vp_api_types.h"
#else
typedef unsigned char VpProfileDataType;
#endif


/************** Device Profile **************/
extern const VpProfileDataType LE9662_DEV_PROFILE_47UH[];   /* Device Configuration Data - 47uH Inductor */

/************** DC Profile **************/
extern const VpProfileDataType DC_FXS_VE960_ABS100V_DEF[];/* DC FXS Defaults - Use for all countries unless country file exists - 23mA Current Feed */

/************** AC Profile **************/
extern const VpProfileDataType AC_FXS_VE960_RF14_600R_DEF[];/* AC FXS RF14 600R Normal Coefficients (Default)  */

/************** Ringing Profile **************/
extern const VpProfileDataType RING_VE960_ABS100V_DEF[]; /* Default Ringing 25Hz 50Vrms Fixed, AC Trip - Use for all countries unless country profile exists */
extern const VpProfileDataType RING_MISLIC_ABS100V_CHINA_TRAPE_9642[]; /* Default Ringing 25Hz 60Vrms Fixed, AC Trip */ 


/************** Tone Profile **************/

/************** Cadence Profile **************/

/************** Caller ID Profile **************/

/************** Metering_Profile **************/
extern const VpProfileDataType METER_LE9662_12KHZ[];  //dyma_20140428

#endif /* ZLR96622_SM2_FULL_H */

