/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "myapp-generated.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface net.Corp.MyApp.Frobber
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:MyAppNetCorpMyAppFrobber
 * @title: MyAppNetCorpMyAppFrobber
 * @short_description: Generated C code for the net.Corp.MyApp.Frobber D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link> D-Bus interface in C.
 */

/* ---- Introspection data for net.Corp.MyApp.Frobber ---- */

static const _ExtendedGDBusArgInfo _my_app_net_corp_my_app_frobber_method_info_hello_world_IN_ARG_greeting =
{
  {
    -1,
    "greeting",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _my_app_net_corp_my_app_frobber_method_info_hello_world_IN_ARG_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_method_info_hello_world_IN_ARG_greeting,
  NULL
};

static const _ExtendedGDBusArgInfo _my_app_net_corp_my_app_frobber_method_info_hello_world_OUT_ARG_response =
{
  {
    -1,
    "response",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _my_app_net_corp_my_app_frobber_method_info_hello_world_OUT_ARG_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_method_info_hello_world_OUT_ARG_response,
  NULL
};

static const _ExtendedGDBusMethodInfo _my_app_net_corp_my_app_frobber_method_info_hello_world =
{
  {
    -1,
    "HelloWorld",
    (GDBusArgInfo **) &_my_app_net_corp_my_app_frobber_method_info_hello_world_IN_ARG_pointers,
    (GDBusArgInfo **) &_my_app_net_corp_my_app_frobber_method_info_hello_world_OUT_ARG_pointers,
    NULL
  },
  "handle-hello-world",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _my_app_net_corp_my_app_frobber_method_info_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_method_info_hello_world,
  NULL
};

static const _ExtendedGDBusArgInfo _my_app_net_corp_my_app_frobber_signal_info_notification_ARG_icon_blob =
{
  {
    -1,
    "icon_blob",
    "ay",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _my_app_net_corp_my_app_frobber_signal_info_notification_ARG_height =
{
  {
    -1,
    "height",
    "i",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _my_app_net_corp_my_app_frobber_signal_info_notification_ARG_messages =
{
  {
    -1,
    "messages",
    "as",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _my_app_net_corp_my_app_frobber_signal_info_notification_ARG_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_signal_info_notification_ARG_icon_blob,
  &_my_app_net_corp_my_app_frobber_signal_info_notification_ARG_height,
  &_my_app_net_corp_my_app_frobber_signal_info_notification_ARG_messages,
  NULL
};

static const _ExtendedGDBusSignalInfo _my_app_net_corp_my_app_frobber_signal_info_notification =
{
  {
    -1,
    "Notification",
    (GDBusArgInfo **) &_my_app_net_corp_my_app_frobber_signal_info_notification_ARG_pointers,
    NULL
  },
  "notification"
};

static const _ExtendedGDBusSignalInfo * const _my_app_net_corp_my_app_frobber_signal_info_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_signal_info_notification,
  NULL
};

static const _ExtendedGDBusPropertyInfo _my_app_net_corp_my_app_frobber_property_info_verbose =
{
  {
    -1,
    "Verbose",
    "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "verbose",
  FALSE
};

static const _ExtendedGDBusPropertyInfo * const _my_app_net_corp_my_app_frobber_property_info_pointers[] =
{
  &_my_app_net_corp_my_app_frobber_property_info_verbose,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _my_app_net_corp_my_app_frobber_interface_info =
{
  {
    -1,
    "net.Corp.MyApp.Frobber",
    (GDBusMethodInfo **) &_my_app_net_corp_my_app_frobber_method_info_pointers,
    (GDBusSignalInfo **) &_my_app_net_corp_my_app_frobber_signal_info_pointers,
    (GDBusPropertyInfo **) &_my_app_net_corp_my_app_frobber_property_info_pointers,
    NULL
  },
  "net-corp-my-app-frobber",
};


/**
 * my_app_net_corp_my_app_frobber_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
my_app_net_corp_my_app_frobber_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info;
}

/**
 * my_app_net_corp_my_app_frobber_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #MyAppNetCorpMyAppFrobber interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
my_app_net_corp_my_app_frobber_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "verbose");
  return property_id_begin - 1;
}



/**
 * MyAppNetCorpMyAppFrobber:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link>.
 */

/**
 * MyAppNetCorpMyAppFrobberIface:
 * @parent_iface: The parent interface.
 * @handle_hello_world: Handler for the #MyAppNetCorpMyAppFrobber::handle-hello-world signal.
 * @get_verbose: Getter for the #MyAppNetCorpMyAppFrobber:verbose property.
 * @notification: Handler for the #MyAppNetCorpMyAppFrobber::notification signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link>.
 */

static void
my_app_net_corp_my_app_frobber_default_init (MyAppNetCorpMyAppFrobberIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * MyAppNetCorpMyAppFrobber::handle-hello-world:
   * @object: A #MyAppNetCorpMyAppFrobber.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_greeting: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-net-Corp-MyApp-Frobber.HelloWorld">HelloWorld()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call my_app_net_corp_my_app_frobber_complete_hello_world() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-hello-world",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MyAppNetCorpMyAppFrobberIface, handle_hello_world),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /* GObject signals for received D-Bus signals: */
  /**
   * MyAppNetCorpMyAppFrobber::notification:
   * @object: A #MyAppNetCorpMyAppFrobber.
   * @arg_icon_blob: Argument.
   * @arg_height: Argument.
   * @arg_messages: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-net-Corp-MyApp-Frobber.Notification">"Notification"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("notification",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (MyAppNetCorpMyAppFrobberIface, notification),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    3, G_TYPE_STRING, G_TYPE_INT, G_TYPE_STRV);

  /* GObject properties for D-Bus properties: */
  /**
   * MyAppNetCorpMyAppFrobber:verbose:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-net-Corp-MyApp-Frobber.Verbose">"Verbose"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("verbose", "Verbose", "Verbose", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

typedef MyAppNetCorpMyAppFrobberIface MyAppNetCorpMyAppFrobberInterface;
G_DEFINE_INTERFACE (MyAppNetCorpMyAppFrobber, my_app_net_corp_my_app_frobber, G_TYPE_OBJECT);

/**
 * my_app_net_corp_my_app_frobber_get_verbose: (skip)
 * @object: A #MyAppNetCorpMyAppFrobber.
 *
 * Gets the value of the <link linkend="gdbus-property-net-Corp-MyApp-Frobber.Verbose">"Verbose"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
my_app_net_corp_my_app_frobber_get_verbose (MyAppNetCorpMyAppFrobber *object)
{
  return MY_APP_NET_CORP_MY_APP_FROBBER_GET_IFACE (object)->get_verbose (object);
}

/**
 * my_app_net_corp_my_app_frobber_set_verbose: (skip)
 * @object: A #MyAppNetCorpMyAppFrobber.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-net-Corp-MyApp-Frobber.Verbose">"Verbose"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
my_app_net_corp_my_app_frobber_set_verbose (MyAppNetCorpMyAppFrobber *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "verbose", value, NULL);
}

/**
 * my_app_net_corp_my_app_frobber_emit_notification:
 * @object: A #MyAppNetCorpMyAppFrobber.
 * @arg_icon_blob: Argument to pass with the signal.
 * @arg_height: Argument to pass with the signal.
 * @arg_messages: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-net-Corp-MyApp-Frobber.Notification">"Notification"</link> D-Bus signal.
 */
void
my_app_net_corp_my_app_frobber_emit_notification (
    MyAppNetCorpMyAppFrobber *object,
    const gchar *arg_icon_blob,
    gint arg_height,
    const gchar *const *arg_messages)
{
  g_signal_emit_by_name (object, "notification", arg_icon_blob, arg_height, arg_messages);
}

/**
 * my_app_net_corp_my_app_frobber_call_hello_world:
 * @proxy: A #MyAppNetCorpMyAppFrobberProxy.
 * @arg_greeting: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-net-Corp-MyApp-Frobber.HelloWorld">HelloWorld()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call my_app_net_corp_my_app_frobber_call_hello_world_finish() to get the result of the operation.
 *
 * See my_app_net_corp_my_app_frobber_call_hello_world_sync() for the synchronous, blocking version of this method.
 */
void
my_app_net_corp_my_app_frobber_call_hello_world (
    MyAppNetCorpMyAppFrobber *proxy,
    const gchar *arg_greeting,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "HelloWorld",
    g_variant_new ("(s)",
                   arg_greeting),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * my_app_net_corp_my_app_frobber_call_hello_world_finish:
 * @proxy: A #MyAppNetCorpMyAppFrobberProxy.
 * @out_response: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to my_app_net_corp_my_app_frobber_call_hello_world().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with my_app_net_corp_my_app_frobber_call_hello_world().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
my_app_net_corp_my_app_frobber_call_hello_world_finish (
    MyAppNetCorpMyAppFrobber *proxy,
    gchar **out_response,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_response);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * my_app_net_corp_my_app_frobber_call_hello_world_sync:
 * @proxy: A #MyAppNetCorpMyAppFrobberProxy.
 * @arg_greeting: Argument to pass with the method invocation.
 * @out_response: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-net-Corp-MyApp-Frobber.HelloWorld">HelloWorld()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See my_app_net_corp_my_app_frobber_call_hello_world() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
my_app_net_corp_my_app_frobber_call_hello_world_sync (
    MyAppNetCorpMyAppFrobber *proxy,
    const gchar *arg_greeting,
    gchar **out_response,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "HelloWorld",
    g_variant_new ("(s)",
                   arg_greeting),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(s)",
                 out_response);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * my_app_net_corp_my_app_frobber_complete_hello_world:
 * @object: A #MyAppNetCorpMyAppFrobber.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @response: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-net-Corp-MyApp-Frobber.HelloWorld">HelloWorld()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
my_app_net_corp_my_app_frobber_complete_hello_world (
    MyAppNetCorpMyAppFrobber *object,
    GDBusMethodInvocation *invocation,
    const gchar *response)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(s)",
                   response));
}

/* ------------------------------------------------------------------------ */

/**
 * MyAppNetCorpMyAppFrobberProxy:
 *
 * The #MyAppNetCorpMyAppFrobberProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MyAppNetCorpMyAppFrobberProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MyAppNetCorpMyAppFrobberProxy.
 */

struct _MyAppNetCorpMyAppFrobberProxyPrivate
{
  GData *qdata;
};

static void my_app_net_corp_my_app_frobber_proxy_iface_init (MyAppNetCorpMyAppFrobberIface *iface);

G_DEFINE_TYPE_WITH_CODE (MyAppNetCorpMyAppFrobberProxy, my_app_net_corp_my_app_frobber_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER, my_app_net_corp_my_app_frobber_proxy_iface_init));

static void
my_app_net_corp_my_app_frobber_proxy_finalize (GObject *object)
{
  MyAppNetCorpMyAppFrobberProxy *proxy = MY_APP_NET_CORP_MY_APP_FROBBER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (my_app_net_corp_my_app_frobber_proxy_parent_class)->finalize (object);
}

static void
my_app_net_corp_my_app_frobber_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _my_app_net_corp_my_app_frobber_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
my_app_net_corp_my_app_frobber_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  error = NULL;
  if (!g_dbus_proxy_call_finish (proxy, res, &error))
    {
      g_warning ("Error setting property `%s' on interface net.Corp.MyApp.Frobber: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
}

static void
my_app_net_corp_my_app_frobber_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  info = _my_app_net_corp_my_app_frobber_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "net.Corp.MyApp.Frobber", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) my_app_net_corp_my_app_frobber_proxy_set_property_cb, (gpointer) info);
  g_variant_unref (variant);
}

static void
my_app_net_corp_my_app_frobber_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], MY_APP_TYPE_NET_CORP_MY_APP_FROBBER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MY_APP_TYPE_NET_CORP_MY_APP_FROBBER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
my_app_net_corp_my_app_frobber_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  MyAppNetCorpMyAppFrobberProxy *proxy = MY_APP_NET_CORP_MY_APP_FROBBER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
my_app_net_corp_my_app_frobber_proxy_get_verbose (MyAppNetCorpMyAppFrobber *object)
{
  MyAppNetCorpMyAppFrobberProxy *proxy = MY_APP_NET_CORP_MY_APP_FROBBER_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "Verbose");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
my_app_net_corp_my_app_frobber_proxy_init (MyAppNetCorpMyAppFrobberProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_PROXY, MyAppNetCorpMyAppFrobberProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), my_app_net_corp_my_app_frobber_interface_info ());
}

static void
my_app_net_corp_my_app_frobber_proxy_class_init (MyAppNetCorpMyAppFrobberProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (MyAppNetCorpMyAppFrobberProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = my_app_net_corp_my_app_frobber_proxy_finalize;
  gobject_class->get_property = my_app_net_corp_my_app_frobber_proxy_get_property;
  gobject_class->set_property = my_app_net_corp_my_app_frobber_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = my_app_net_corp_my_app_frobber_proxy_g_signal;
  proxy_class->g_properties_changed = my_app_net_corp_my_app_frobber_proxy_g_properties_changed;


  my_app_net_corp_my_app_frobber_override_properties (gobject_class, 1);
}

static void
my_app_net_corp_my_app_frobber_proxy_iface_init (MyAppNetCorpMyAppFrobberIface *iface)
{
  iface->get_verbose = my_app_net_corp_my_app_frobber_proxy_get_verbose;
}

/**
 * my_app_net_corp_my_app_frobber_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call my_app_net_corp_my_app_frobber_proxy_new_finish() to get the result of the operation.
 *
 * See my_app_net_corp_my_app_frobber_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
my_app_net_corp_my_app_frobber_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.Corp.MyApp.Frobber", NULL);
}

/**
 * my_app_net_corp_my_app_frobber_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to my_app_net_corp_my_app_frobber_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with my_app_net_corp_my_app_frobber_proxy_new().
 *
 * Returns: (transfer full) (type MyAppNetCorpMyAppFrobberProxy): The constructed proxy object or %NULL if @error is set.
 */
MyAppNetCorpMyAppFrobber *
my_app_net_corp_my_app_frobber_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MY_APP_NET_CORP_MY_APP_FROBBER (ret);
  else
    return NULL;
}

/**
 * my_app_net_corp_my_app_frobber_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See my_app_net_corp_my_app_frobber_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MyAppNetCorpMyAppFrobberProxy): The constructed proxy object or %NULL if @error is set.
 */
MyAppNetCorpMyAppFrobber *
my_app_net_corp_my_app_frobber_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "net.Corp.MyApp.Frobber", NULL);
  if (ret != NULL)
    return MY_APP_NET_CORP_MY_APP_FROBBER (ret);
  else
    return NULL;
}


/**
 * my_app_net_corp_my_app_frobber_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like my_app_net_corp_my_app_frobber_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call my_app_net_corp_my_app_frobber_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See my_app_net_corp_my_app_frobber_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
my_app_net_corp_my_app_frobber_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.Corp.MyApp.Frobber", NULL);
}

/**
 * my_app_net_corp_my_app_frobber_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to my_app_net_corp_my_app_frobber_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with my_app_net_corp_my_app_frobber_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type MyAppNetCorpMyAppFrobberProxy): The constructed proxy object or %NULL if @error is set.
 */
MyAppNetCorpMyAppFrobber *
my_app_net_corp_my_app_frobber_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return MY_APP_NET_CORP_MY_APP_FROBBER (ret);
  else
    return NULL;
}

/**
 * my_app_net_corp_my_app_frobber_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like my_app_net_corp_my_app_frobber_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See my_app_net_corp_my_app_frobber_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type MyAppNetCorpMyAppFrobberProxy): The constructed proxy object or %NULL if @error is set.
 */
MyAppNetCorpMyAppFrobber *
my_app_net_corp_my_app_frobber_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "net.Corp.MyApp.Frobber", NULL);
  if (ret != NULL)
    return MY_APP_NET_CORP_MY_APP_FROBBER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * MyAppNetCorpMyAppFrobberSkeleton:
 *
 * The #MyAppNetCorpMyAppFrobberSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * MyAppNetCorpMyAppFrobberSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #MyAppNetCorpMyAppFrobberSkeleton.
 */

struct _MyAppNetCorpMyAppFrobberSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_my_app_net_corp_my_app_frobber_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], MY_APP_TYPE_NET_CORP_MY_APP_FROBBER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, MY_APP_TYPE_NET_CORP_MY_APP_FROBBER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_my_app_net_corp_my_app_frobber_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_my_app_net_corp_my_app_frobber_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_my_app_net_corp_my_app_frobber_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _my_app_net_corp_my_app_frobber_skeleton_vtable =
{
  _my_app_net_corp_my_app_frobber_skeleton_handle_method_call,
  _my_app_net_corp_my_app_frobber_skeleton_handle_get_property,
  _my_app_net_corp_my_app_frobber_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return my_app_net_corp_my_app_frobber_interface_info ();
}

static GDBusInterfaceVTable *
my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_my_app_net_corp_my_app_frobber_skeleton_vtable;
}

static GVariant *
my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_my_app_net_corp_my_app_frobber_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _my_app_net_corp_my_app_frobber_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _my_app_net_corp_my_app_frobber_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _my_app_net_corp_my_app_frobber_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "net.Corp.MyApp.Frobber", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _my_app_net_corp_my_app_frobber_emit_changed (gpointer user_data);

static void
my_app_net_corp_my_app_frobber_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _my_app_net_corp_my_app_frobber_emit_changed (skeleton);
}

static void
_my_app_net_corp_my_app_frobber_on_signal_notification (
    MyAppNetCorpMyAppFrobber *object,
    const gchar *arg_icon_blob,
    gint arg_height,
    const gchar *const *arg_messages)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(^ayi^as)",
                   arg_icon_blob,
                   arg_height,
                   arg_messages));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "net.Corp.MyApp.Frobber", "Notification",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void my_app_net_corp_my_app_frobber_skeleton_iface_init (MyAppNetCorpMyAppFrobberIface *iface);
G_DEFINE_TYPE_WITH_CODE (MyAppNetCorpMyAppFrobberSkeleton, my_app_net_corp_my_app_frobber_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER, my_app_net_corp_my_app_frobber_skeleton_iface_init));

static void
my_app_net_corp_my_app_frobber_skeleton_finalize (GObject *object)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);
  guint n;
  for (n = 0; n < 1; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (my_app_net_corp_my_app_frobber_skeleton_parent_class)->finalize (object);
}

static void
my_app_net_corp_my_app_frobber_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_my_app_net_corp_my_app_frobber_emit_changed (gpointer user_data)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *l;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "net.Corp.MyApp.Frobber",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (l = connections; l != NULL; l = l->next)
        {
          GDBusConnection *connection = l->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_my_app_net_corp_my_app_frobber_schedule_emit_changed (MyAppNetCorpMyAppFrobberSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
my_app_net_corp_my_app_frobber_skeleton_notify (GObject      *object,
  GParamSpec *pspec)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _my_app_net_corp_my_app_frobber_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
my_app_net_corp_my_app_frobber_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 1);
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL)
        _my_app_net_corp_my_app_frobber_schedule_emit_changed (skeleton, _my_app_net_corp_my_app_frobber_property_info_pointers[prop_id - 1], prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
my_app_net_corp_my_app_frobber_skeleton_init (MyAppNetCorpMyAppFrobberSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_SKELETON, MyAppNetCorpMyAppFrobberSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 1);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
}

static gboolean 
my_app_net_corp_my_app_frobber_skeleton_get_verbose (MyAppNetCorpMyAppFrobber *object)
{
  MyAppNetCorpMyAppFrobberSkeleton *skeleton = MY_APP_NET_CORP_MY_APP_FROBBER_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
my_app_net_corp_my_app_frobber_skeleton_class_init (MyAppNetCorpMyAppFrobberSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (MyAppNetCorpMyAppFrobberSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = my_app_net_corp_my_app_frobber_skeleton_finalize;
  gobject_class->get_property = my_app_net_corp_my_app_frobber_skeleton_get_property;
  gobject_class->set_property = my_app_net_corp_my_app_frobber_skeleton_set_property;
  gobject_class->notify       = my_app_net_corp_my_app_frobber_skeleton_notify;


  my_app_net_corp_my_app_frobber_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = my_app_net_corp_my_app_frobber_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = my_app_net_corp_my_app_frobber_skeleton_dbus_interface_get_vtable;
}

static void
my_app_net_corp_my_app_frobber_skeleton_iface_init (MyAppNetCorpMyAppFrobberIface *iface)
{
  iface->notification = _my_app_net_corp_my_app_frobber_on_signal_notification;
  iface->get_verbose = my_app_net_corp_my_app_frobber_skeleton_get_verbose;
}

/**
 * my_app_net_corp_my_app_frobber_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-net-Corp-MyApp-Frobber.top_of_page">net.Corp.MyApp.Frobber</link>.
 *
 * Returns: (transfer full) (type MyAppNetCorpMyAppFrobberSkeleton): The skeleton object.
 */
MyAppNetCorpMyAppFrobber *
my_app_net_corp_my_app_frobber_skeleton_new (void)
{
  return MY_APP_NET_CORP_MY_APP_FROBBER (g_object_new (MY_APP_TYPE_NET_CORP_MY_APP_FROBBER_SKELETON, NULL));
}

