#!/bin/sh
#
# This script is called with the following parameters:
# interface tty speed local-address prefix-length remote-address ipparam
#

WAN_IF=$1

#Enable SLAAC mode
echo 1 > /proc/sys/net/ipv6/conf/$WAN_IF/autoconf	

#Start up dhcp6c
/userfs/bin/dhcp6c -e -c /var/run/$WAN_IF/dhcp6c.conf -p /var/run/$WAN_IF/dhcp6c.pid -x /var/run/$WAN_IF/pd6 $WAN_IF &

