/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanService */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanService
#define _Included_com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* Header for class com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanService */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanService
#define _Included_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* Header for class com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanService */
#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanService
#define _Included_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* Header for class com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbService */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbService
#define _Included_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* Header for class com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysService */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysService
#define _Included_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* Header for class com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventService */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventService
#define _Included_com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif


/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanServiceImp */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanServiceImp
 * Method:    wlanSetStateJni
 * Signature: (IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wlanservice_CtWlanServiceImp_wlanSetStateJni
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif


//++++++++++++++++++++       Lan     +++++++++++++++++++++++++++++++++++++++++++++++

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetNetInfoJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetNetInfoJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanSetDevAccessPermissionJni
 * Signature: (Ljava/lang/String;ZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanSetDevAccessPermissionJni
  (JNIEnv *, jobject, jstring, jboolean, jboolean);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetDevInternetAccessBlacklistJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetDevInternetAccessBlacklistJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetDevStorageAccessBlacklistJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetDevStorageAccessBlacklistJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetDevBandwidthJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetDevBandwidthJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanSetDevMaxBandwidthJni
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanSetDevMaxBandwidthJni
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetDevMaxBandwidthJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetDevMaxBandwidthJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanGetPortStatusJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanGetPortStatusJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp
 * Method:    lanSetDevStatsStatusJni
 * Signature: (Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_lanservice_CtLanServiceImp_lanSetDevStatsStatusJni
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif










//++++++++++++++++  Wan          +++++++++++++++++++++++++++++++++++++++++++++++++
#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanGetIfStatsJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanGetIfStatsJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanGetPppoeAccountJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanGetPppoeAccountJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanCreateL2tpTunnelJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanCreateL2tpTunnelJni
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanRemoveL2tpTunnelJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanRemoveL2tpTunnelJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanAttachL2tpTunnelJni
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanAttachL2tpTunnelJni
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanDetachL2tpTunnelJni
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanDetachL2tpTunnelJni
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp
 * Method:    wanGetL2tpTunnelStatusJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_wanservice_CtWanServiceImp_wanGetL2tpTunnelStatusJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif



//++++++++++++++++++++++  USB  ++++++++++++++++++++++++++++++++++++++++++++++


#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbRegisterJni
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbRegisterJni
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbUnregisterJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbUnregisterJni
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbLockJni
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbLockJni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbUnlockJni
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbUnlockJni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbOpenJni
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbOpenJni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbDataAvailableJni
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbDataAvailableJni
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbReadJni
 * Signature: (I[BIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbReadJni
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbWriteJni
 * Signature: (I[BII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbWriteJni
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbSetSerialJni
 * Signature: (IIIIIZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbSetSerialJni
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp
 * Method:    usbCloseJni
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_usbservice_CtUsbServiceImp_usbCloseJni
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif








//+++++++++++++++++++++++++   SYS     ++++++++++++++++++++++++++++++++++++++++++++++

/* Header for class com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
 * Method:    sysGetCpuUsageJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp_sysGetCpuUsageJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
 * Method:    sysGetMemUsageJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp_sysGetMemUsageJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
 * Method:    sysGetIpAddrJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp_sysGetIpAddrJni
  (JNIEnv *, jobject);

/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp
 * Method:    sysGetLoidJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_sysservice_CtSysServiceImp_sysGetLoidJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif


//+++++++++++++++++++++++++    event  ++++++++++++++++++++++++++++++++++++++++++++++++

/* Header for class com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventServiceImp */

#ifndef _Included_com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventServiceImp
#define _Included_com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventServiceImp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventServiceImp
 * Method:    eventInformJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chinatelecom_smartgateway_deviceservice_eventservice_CtEventServiceImp_eventInformJni
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
